export function createPalaceMenu(api){
 const defaults={difficulty:4,timer:'99',master:100,bgm:100,sfx:100};let options={...defaults};try{const saved=JSON.parse(localStorage.getItem('palace-options-v1'));for(const key of Object.keys(defaults))if(saved&&saved[key]!==undefined)options[key]=saved[key]}catch{}
 options.difficulty=Math.max(1,Math.min(8,Number(options.difficulty)||4));options.timer=options.timer==='infinite'?'infinite':String(Math.max(15,Math.min(99,Number(options.timer)||99)));for(const key of ['master','bgm','sfx'])options[key]=Math.max(0,Math.min(100,Number(options[key])||0));
 let mode='home',selected=0;const sounds=new Set(),music=new Audio('./title-bgm.mp3');music.loop=true;
 const overlay=document.createElement('div');overlay.id='palaceMenu';overlay.style.cssText='position:fixed;inset:0;z-index:40;background:#05050d';
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%';overlay.appendChild(canvas);const context=canvas.getContext('2d');
 const panel=document.createElement('div');panel.style.cssText='position:absolute;left:50%;top:72%;transform:translateX(-50%);text-align:center;min-width:260px';overlay.appendChild(panel);document.body.appendChild(overlay);
 const musicPrompt=document.createElement('button');musicPrompt.id='enableBgm';musicPrompt.textContent='點擊播放 BGM';musicPrompt.hidden=true;musicPrompt.style.cssText='position:absolute;right:16px;top:16px;font-size:14px;padding:8px 12px';overlay.appendChild(musicPrompt);
 function playMusic(){if(overlay.hidden)return;volume();music.play().then(()=>{musicPrompt.hidden=true;if(overlay.hidden)music.pause()}).catch(error=>{musicPrompt.textContent=error.name==='NotAllowedError'?'點擊播放 BGM':'重試播放 BGM';musicPrompt.hidden=false})}
 musicPrompt.addEventListener('click',playMusic);document.addEventListener('pointerdown',playMusic,true);document.addEventListener('keydown',playMusic,true);
 const homeButton=document.createElement('button');homeButton.textContent='Menu';homeButton.style.cssText='font-size:11px;padding:3px 6px;border-radius:4px';document.querySelector('#inputPanel').appendChild(homeButton);
 let layers=[],animation,atlases=[],started=performance.now();const ready=Promise.all([fetch('./title_layers.json?v=02344').then(response=>response.json()).then(async data=>{layers=await Promise.all(data.layers.map(async layer=>{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src='./'+layer.file+'?v=02344'});return {...layer,image}}))}),fetch('./title_animation_webp.json?v=02344').then(response=>response.json()).then(async data=>{atlases=await Promise.all(Object.values(data.animated).map(entry=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src='./'+entry.file+'?v=02344'})));animation=data})]).then(()=>{started=performance.now();draw()});
 function draw(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const fit=Math.min(innerWidth/1280,innerHeight/720),left=(innerWidth-1280*fit)/2,top=(innerHeight-720*fit)/2;context.clearRect(0,0,innerWidth,innerHeight);context.translate(left,top);context.scale(fit,fit);context.beginPath();context.rect(0,0,1280,720);context.clip();const tick=Math.floor((performance.now()-started)*60/1000);for(const layer of layers){const action=layer.sprite[0];if(layer.sprite[0]===10&&layer.sprite[1]===1)continue;if(animation&&[21,30].includes(action)){const entry=animation.animated[String(action)];context.drawImage(atlases[action===21?0:1],entry.x,entry.y)}else if(action===0){context.drawImage(layer.image,640-layer.axisX,-layer.axisY+Math.min(0,-75+Math.min(tick,15)*5))}else context.drawImage(layer.image,640-layer.axisX,-layer.axisY);if(layer===layers[0]&&layers[7]){const star=layers[7];context.save();context.globalCompositeOperation='lighter';context.globalAlpha=50/256;for(const [x,y] of [[330,-120],[1220,90]]){const startX=((640+x-star.axisX-24*tick)%star.image.width+star.image.width)%star.image.width,startY=((y-star.axisY+10*tick)%star.image.height+star.image.height)%star.image.height;for(let px=startX-star.image.width;px<1280;px+=star.image.width)for(let py=startY-star.image.height;py<720;py+=star.image.height)context.drawImage(star.image,px,py)}context.restore()}}}
 function volume(){music.volume=options.master*options.bgm/10000;for(const sound of sounds)sound.volume=options.master*options.sfx/10000}
 function sound(audio){sounds.add(audio);audio.volume=options.master*options.sfx/10000;audio.addEventListener('ended',()=>sounds.delete(audio),{once:true});audio.addEventListener('error',()=>sounds.delete(audio),{once:true});return audio}
 function button(label,action){const element=document.createElement('button');element.textContent=label;element.style.cssText='display:block;margin:auto;border:0;background:transparent;color:#ffd66b;text-shadow:0 0 8px #fff;font:32px Georgia;padding:2px 14px';element.addEventListener('click',action);panel.appendChild(element);return element}
 function save(){try{localStorage.setItem('palace-options-v1',JSON.stringify(options))}catch{}volume()}
 function showHome(){mode='home';overlay.hidden=false;panel.style.top='72%';panel.replaceChildren();for(const [index,label] of ['VS','Training','Watch','Options'].entries()){const element=button(label,()=>index===3?showOptions():start(label.toLowerCase()));element.style.opacity=index===selected?'1':'.65'}api.pause(true);volume();playMusic()}
 async function start(next){panel.replaceChildren();button('Loading…',()=>{});await api.ready();mode=next;overlay.hidden=true;music.pause();api.start(next,next==='training'?'infinite':options.timer);api.pause(false)}
 function showOptions(){mode='options';volume();playMusic();panel.style.top='28%';panel.replaceChildren();const box=document.createElement('div');box.style.cssText='padding:18px;background:#080b27dd;border:1px solid #bda451;border-radius:8px;color:white';panel.appendChild(box);
  for(const [key,label,min,max] of [['difficulty','Difficulty',1,8],['master','Master Volume',0,100],['bgm','BGM Volume',0,100],['sfx','SFX Volume',0,100]]){const row=document.createElement('label');row.style.cssText='display:block;padding:8px;text-align:left';const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.value=options[key];const value=document.createElement('span');value.textContent=options[key]+(key==='difficulty'?'':'%');row.append(label+' ',input,value);input.addEventListener('input',()=>{options[key]=Number(input.value);value.textContent=input.value+(key==='difficulty'?'':'%');save()});box.appendChild(row)}
  const timer=document.createElement('select');timer.id='optionTimer';for(const value of ['infinite',...Array.from({length:85},(_,index)=>String(index+15))]){const item=document.createElement('option');item.value=value;item.textContent=value==='infinite'?'None':value;timer.appendChild(item)}timer.value=options.timer;timer.addEventListener('change',()=>{options.timer=timer.value;save()});box.append('Timer ',timer);button('Key Config',()=>api.keyConfig());button('Back',showHome);
 }
 homeButton.addEventListener('click',showHome);window.addEventListener('resize',draw);
 document.addEventListener('keydown',event=>{if(overlay.hidden||document.querySelector('dialog[open]'))return;if(event.target.matches('input,select'))return;event.preventDefault();event.stopImmediatePropagation();if(mode==='home'){if(event.code==='ArrowDown'||event.code==='ArrowUp'){selected=(selected+(event.code==='ArrowDown'?1:3))%4;showHome()}else if(event.code==='Enter'){selected===3?showOptions():start(['vs','training','watch'][selected])}}else if(event.code==='Escape')showHome()},true);
 showHome();
 function animate(){if(!overlay.hidden)draw();requestAnimationFrame(animate)}requestAnimationFrame(animate);
 const requested=new URLSearchParams(location.search).get('mode');if(['vs','training','watch'].includes(requested))start(requested);
 return {ready,sound,options,start,showHome,isWatch:()=>mode==='watch',isHome:()=>!overlay.hidden};
}
