import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {assetUrl} from '../../Engine/asset-paths.js?v=02362';
import {lightSeeds} from '../../Engine/falling-lights.js?v=02368';
import {effectPulse} from './select-effects-timing.js?v=selection8';

export function createSelectStage(parent){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.id='selectStage3D';renderer.domElement.style.cssText='position:absolute;pointer-events:none';parent.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x061b40);scene.add(new THREE.HemisphereLight(0xd9faff,0x3977be,2));
 let camera,mixer,sphere,settings,visible=false,time=0,accumulator=0,renderedFrames=0,innerGlow,outerGlow,glare,particles,particleHalos;
 const surfaceGlares=[],rearGlares=[];
 const portraitMeshes=[];
 function setPortraits(entries){const focal=360/Math.tan(THREE.MathUtils.degToRad(settings.fov/2)),depth=10;for(const [index,entry] of entries.entries()){let mesh=portraitMeshes[index];if(!mesh){mesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({transparent:true,depthTest:false,depthWrite:false,toneMapped:false}));mesh.renderOrder=1;mesh.name='SelectionPortrait'+index;scene.add(mesh);portraitMeshes[index]=mesh}mesh.visible=!!entry;if(!entry)continue;if(mesh.userData.image!==entry.image){mesh.material.map?.dispose();const texture=new THREE.Texture(entry.image);texture.colorSpace=THREE.SRGBColorSpace;texture.needsUpdate=true;mesh.material.map=texture;mesh.material.needsUpdate=true;mesh.userData.image=entry.image}mesh.scale.set(entry.w*depth/focal,entry.h*depth/focal,1);mesh.position.set((entry.x+entry.w/2-640)*depth/focal,camera.position.y+(360-entry.y-entry.h/2)*depth/focal,camera.position.z-depth)}}
 const effects=new THREE.Group();scene.add(effects);
 const vertexShader='varying vec2 effectUv;void main(){effectUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}';
 function plane(name,size,fragmentShader){const material=new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader,fragmentShader:'uniform float time;varying vec2 effectUv;'+fragmentShader,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,depthTest:true,toneMapped:false});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(size,size),material);mesh.name=name;effects.add(mesh);return mesh}
 function addEffects(){
  innerGlow=plane('SelectionInnerGlow',3.5,'void main(){float radius=length(effectUv-0.5)*2.0;float edge=exp(-pow((radius-0.78)/0.065,2.0));float inside=exp(-pow((radius-0.70)/0.12,2.0))*(1.0-smoothstep(0.70,0.90,radius));float pulse=0.93+0.07*sin(time*1.4);gl_FragColor=vec4(vec3(0.58,0.92,1.0),(edge*0.32+inside*0.15)*pulse);}');
  outerGlow=plane('SelectionOuterGlow',4.6,'void main(){float radius=length(effectUv-0.5)*2.0;float halo=exp(-pow((radius-0.62)/0.09,2.0));float bloom=exp(-pow((radius-0.65)/0.19,2.0));float core=exp(-pow((radius-0.61)/0.014,2.0));gl_FragColor=vec4(vec3(0.50,0.87,1.0),halo*0.18+bloom*0.055+core*0.24);}');
  glare=plane('SelectionRearGlare',13,'uniform float beamStrength[7];void main(){vec2 point=effectUv-0.5;float radius=length(point);float beams=0.0;for(int index=0;index<7;index++){float axis=float(index)*0.8976+0.18+sin(time*0.45+float(index)*1.1)*0.24;vec2 direction=vec2(cos(axis),sin(axis));float along=dot(point,direction);float across=dot(point,vec2(-direction.y,direction.x));float width=0.0012+max(along,0.0)*0.004;float shaft=exp(-pow(across/width,2.0));float envelope=smoothstep(0.0,0.02,along)*(1.0-smoothstep(0.15,0.23,along));beams+=shaft*envelope*beamStrength[index];}gl_FragColor=vec4(vec3(0.66,0.89,1.0),min(beams,1.0)*0.85*smoothstep(0.134,0.139,length(point-vec2(0.0,0.0026))));}');
  const flareShader='uniform float flareAlpha;void main(){vec2 point=effectUv-0.5;float haloRadius=length(point);float radius=haloRadius*(1.7/0.88);float angle=atan(point.y,point.x);float spike=0.045+0.39*pow(abs(cos(angle*4.0)),28.0);float rays=(1.0-smoothstep(spike*0.55,spike,radius))*(1.0-smoothstep(0.03,0.46,radius));float core=exp(-radius*radius*420.0);float halo=exp(-haloRadius*haloRadius*22.0)*0.28*(1.0-smoothstep(0.4,0.5,haloRadius));float pulse=flareAlpha;gl_FragColor=vec4(vec3(0.83,0.96,1.0),(core+halo+rays*0.65)*pulse);}';
  const rear=plane('SelectionRearReflectionStar',1.7,flareShader);rear.position.set(1.12,1.20,-.65);rear.renderOrder=4;rear.material.depthTest=false;rearGlares.push(rear);
  glare.material.uniforms.beamStrength={value:Array(7).fill(0)};rear.material.uniforms.flareAlpha={value:0};
  surfaceGlares.push({x:-1.06,y:.83,size:195,phase:0},{x:.85,y:-.86,size:126,phase:2.1});
  const count=96,sharedSeeds=lightSeeds(count),seeds=new Float32Array(count*3),sizes=new Float32Array(count),kinds=new Float32Array(count);for(let index=0;index<count;index++){seeds[index*3]=((index*0.61803398875)%1)*11-5.5;seeds[index*3+1]=(index*0.38196601125)%1;seeds[index*3+2]=((index*0.754877666)%1)*2-1;const variation=(index*0.41421356)%1;sizes[index]=(3+variation*5)*(0.55+((index*0.73205081)%1)*1.1);seeds[index*3]=sharedSeeds[index].x;seeds[index*3+1]=sharedSeeds[index].phase;seeds[index*3+2]=sharedSeeds[index].z;sizes[index]=sharedSeeds[index].size;kinds[index]=sharedSeeds[index].star?1:0}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(seeds,3));geometry.setAttribute('pointSize',new THREE.BufferAttribute(sizes,1));geometry.setAttribute('pointKind',new THREE.BufferAttribute(kinds,1));
  const material=new THREE.ShaderMaterial({uniforms:{time:{value:0},pixelRatio:{value:renderer.getPixelRatio()},viewportScale:{value:1},viewportHeight:{value:720},particleScale:{value:2}},vertexShader:'uniform float time;uniform float pixelRatio;uniform float viewportScale;uniform float viewportHeight;uniform float particleScale;attribute float pointSize;attribute float pointKind;varying float brightness;varying float kind;varying float impactLevel;void main(){float phase=fract(position.y+time*(0.085+pointSize*0.003));float travel=min(phase/0.82,1.0);vec3 point=vec3(position.x+sin(position.y*6.283+travel*2.0)*0.08,5.4,position.z+0.4);float impact=smoothstep(0.82,0.89,phase);impactLevel=impact;brightness=smoothstep(0.0,0.06,phase)*(1.0-smoothstep(0.90,1.0,phase));kind=pointKind;vec4 projected=modelViewMatrix*vec4(point,1.0);gl_Position=projectionMatrix*projected;float landingInset=20.0+40.0*fract(sin(position.y*127.1+position.x*311.7)*43758.5453);gl_Position.y=mix(gl_Position.y,(-1.0+2.0*landingInset/viewportHeight)*gl_Position.w,travel);gl_Position.x=(position.x/5.5*0.90+sin(position.y*6.283+travel*2.0)*0.008)*gl_Position.w;gl_PointSize=pointSize*particleScale*pixelRatio*viewportScale*(1.0+(1.0-pointKind)*impact*1.5);}',fragmentShader:'varying float brightness;varying float kind;void main(){vec2 point=gl_PointCoord-0.5;float radius=length(point);float angle=atan(point.y,point.x);float core=exp(-radius*radius*65.0);float glow=exp(-radius*radius*18.0)*0.3;float tip=0.045+0.43*pow(abs(cos(angle*4.0)),24.0);float star=(1.0-smoothstep(tip*0.5,tip,radius))*(1.0-smoothstep(0.02,0.49,radius));float alpha=mix(core+glow,star+glow*0.3,kind);gl_FragColor=vec4(vec3(0.72,0.94,1.0),alpha*brightness*0.8);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});particles=new THREE.Points(geometry,material);particles.frustumCulled=false;particles.name='SelectionFallingLights';scene.add(particles);
  const haloMaterial=new THREE.ShaderMaterial({uniforms:material.uniforms,vertexShader:material.vertexShader.replace('(1.0+(1.0-pointKind)*impact*1.5)','(1.0+impact*2.0)').replace('gl_PointSize=pointSize','gl_PointSize=2.4*pointSize'),fragmentShader:'varying float brightness;varying float impactLevel;void main(){float radius=length(gl_PointCoord-0.5);float halo=exp(-radius*radius*22.0)*(1.0-smoothstep(0.35,0.50,radius));gl_FragColor=vec4(vec3(0.48,0.83,1.0),halo*brightness*0.32*(1.0+impactLevel*1.6));}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});particleHalos=new THREE.Points(geometry,haloMaterial);particleHalos.frustumCulled=false;particleHalos.name='SelectionAirborneLightHalos';particleHalos.material.depthTest=false;particles.material.depthTest=false;scene.add(particleHalos);for(const [layer,order] of [0.5,1.5,7].entries()){const subset=geometry.clone();subset.setDrawRange(layer*32,32);const body=layer===0?particles:new THREE.Points(subset,material),halo=layer===0?particleHalos:new THREE.Points(subset,haloMaterial);if(layer===0){particles.geometry=subset;particleHalos.geometry=subset}body.frustumCulled=halo.frustumCulled=false;body.renderOrder=order;halo.renderOrder=order-.01;if(layer>0)scene.add(body,halo)}
 }
 function resize(){if(!camera)return;const fit=Math.min(innerWidth/1280,innerHeight/720),width=1280*fit,height=720*fit;renderer.setSize(width,height,false);Object.assign(renderer.domElement.style,{width:width+'px',height:height+'px',left:(innerWidth-width)/2+'px',top:(innerHeight-height)/2+'px'});camera.aspect=width/height;camera.updateProjectionMatrix();if(particles){particles.material.uniforms.viewportScale.value=fit;particles.material.uniforms.viewportHeight.value=height}}
 const ready=Promise.all([new THREE.TextureLoader().loadAsync(assetUrl('./Stage/Select/background.webp?v=selection8')),fetch(assetUrl('./Stage/Select/select-stage.json?v=selection8')).then(response=>{if(!response.ok)throw Error('Select stage settings');return response.json()}),fetch(assetUrl('./Stage/Select/Select.glb.gz?v=selection8')).then(response=>{if(!response.ok)throw Error('Select stage model');return new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()})]).then(async ([background,config,buffer])=>{background.colorSpace=THREE.SRGBColorSpace;scene.background=background;settings=config;camera=new THREE.PerspectiveCamera(config.fov,16/9,.01,1000);camera.position.fromArray(config.cameraPosition);const model=await new GLTFLoader().parseAsync(buffer,'./');scene.add(model.scene);sphere=model.scene.getObjectByName(config.target);if(!sphere)model.scene.traverse(node=>{if(node.userData.name===config.target)sphere=node});if(!sphere)throw Error('Selection Sphere.004 missing');model.scene.traverse(node=>{if(!node.isMesh)return;for(const material of Array.isArray(node.material)?node.material:[node.material]){if(/^sky/i.test(node.name))material.depthWrite=false;if(node===sphere)material.side=THREE.FrontSide;if(node===sphere||node.name==='Sphere.005'){node.renderOrder=node===sphere?3:2;material.transparent=true;material.depthTest=false;material.depthWrite=false}}});mixer=new THREE.AnimationMixer(model.scene);for(const clip of model.animations)mixer.clipAction(clip).play();addEffects();resize();render(0)});
 const center=new THREE.Vector3();
 function render(dt){if(!camera||!mixer)return;accumulator+=Math.max(0,dt);const steps=Math.floor((accumulator+1e-9)*30);if(!steps&&renderedFrames)return;const elapsed=steps/30;accumulator-=elapsed;time+=elapsed;mixer.update(elapsed);sphere.getWorldPosition(center);effects.position.copy(center);for(const mesh of [innerGlow,outerGlow,glare,...rearGlares]){mesh.quaternion.copy(camera.quaternion);mesh.material.uniforms.time.value=time}glare.material.uniforms.beamStrength.value=Array.from({length:7},(_,index)=>effectPulse(Math.round(time*60),index));rearGlares[0].material.uniforms.flareAlpha.value=effectPulse(Math.round(time*60),2,'star');rearGlares[0].position.x=1.12-20*(camera.position.z-center.z+.65)/(360/Math.tan(THREE.MathUtils.degToRad(settings.fov/2)));innerGlow.position.z=.12;innerGlow.renderOrder=10;outerGlow.position.z=.1;outerGlow.renderOrder=11;glare.position.z=-1.6;glare.renderOrder=5;glare.material.depthTest=false;particles.material.uniforms.time.value=time;renderer.render(scene,camera);renderedFrames++}
 function drawSurfaceGlares(context){if(!camera||!sphere)return;for(const flare of surfaceGlares){const point=center.clone().add(new THREE.Vector3(flare.x,flare.y,Math.sqrt(Math.max(0,1.4*1.4-flare.x*flare.x-flare.y*flare.y))+.04)).project(camera),x=(point.x+1)*640,y=(1-point.y)*360,pulse=effectPulse(Math.round(time*60),surfaceGlares.indexOf(flare),'star'),radius=flare.size/2;context.save();context.translate(x,y);context.globalAlpha=pulse;context.globalCompositeOperation='lighter';const halo=context.createRadialGradient(0,0,0,0,0,radius*.95);halo.addColorStop(0,'rgba(255,255,255,0.95)');halo.addColorStop(.12,'rgba(210,245,255,0.65)');halo.addColorStop(1,'rgba(150,225,255,0)');context.fillStyle=halo;context.fillRect(-radius,-radius,radius*2,radius*2);context.beginPath();for(let index=0;index<16;index++){const angle=index*Math.PI/8-Math.PI/2,length=index%2?radius*.055:radius*(index%4===0?1:.65),pointX=Math.cos(angle)*length,pointY=Math.sin(angle)*length;if(!index)context.moveTo(pointX,pointY);else context.lineTo(pointX,pointY)}context.closePath();context.fillStyle='rgba(235,250,255,0.9)';context.fill();context.restore()}}
 window.addEventListener('resize',resize);
 return {ready,setPortraits,drawSurfaceGlares,render:dt=>{if(visible)render(dt)},setVisible:value=>{visible=value;if(!value)accumulator=0;renderer.domElement.hidden=!value},snapshot:()=>({loaded:!!mixer,visible,time,fps:30,renderedFrames,cameraPosition:camera?.position.toArray(),cameraBlender:settings?.cameraBlender,portraitLayers:portraitMeshes.filter(mesh=>mesh.visible).length,portraitRenderOrder:1,globeRenderOrder:sphere?.renderOrder,reflectionStars:surfaceGlares.length+rearGlares.length,landingViewportHeight:particles?.material.uniforms.viewportHeight.value,landingShader:particles?.material.vertexShader,particleScale:particles?.material.uniforms.particleScale.value,starParticles:particles?Array.from(particles.geometry.attributes.pointKind.array).filter(value=>value===1).length:0,beamAngle:Math.sin(time*.45)*.24,glowTarget:settings?.target,innerGlow:!!innerGlow,outerGlow:!!outerGlow,glare:!!glare,particleLayers:[32,32,32],particleOrders:[.5,1.5,7],fallingLights:particles?.geometry.attributes.position.count||0,animations:settings?.animations})};
}

