import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {assetUrl} from '../../Engine/asset-paths.js?v=02362';

export function createSelectStage(parent){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.id='selectStage3D';renderer.domElement.style.cssText='position:absolute;pointer-events:none';parent.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x061b40);scene.add(new THREE.HemisphereLight(0xd9faff,0x3977be,2));
 let camera,mixer,sphere,settings,visible=false,time=0,accumulator=0,renderedFrames=0,innerGlow,outerGlow,glare,particles,particleHalos;
 const surfaceGlares=[],rearGlares=[];
 const effects=new THREE.Group();scene.add(effects);
 const vertexShader='varying vec2 effectUv;void main(){effectUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}';
 function plane(name,size,fragmentShader){const material=new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader,fragmentShader:'uniform float time;varying vec2 effectUv;'+fragmentShader,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,depthTest:true,toneMapped:false});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(size,size),material);mesh.name=name;effects.add(mesh);return mesh}
 function addEffects(){
  innerGlow=plane('SelectionInnerGlow',3.5,'void main(){float radius=length(effectUv-0.5)*2.0;float edge=exp(-pow((radius-0.78)/0.065,2.0));float inside=exp(-pow((radius-0.70)/0.12,2.0))*(1.0-smoothstep(0.70,0.90,radius));float pulse=0.93+0.07*sin(time*1.4);gl_FragColor=vec4(vec3(0.58,0.92,1.0),(edge*0.32+inside*0.15)*pulse);}');
  outerGlow=plane('SelectionOuterGlow',4.6,'void main(){float radius=length(effectUv-0.5)*2.0;float halo=exp(-pow((radius-0.62)/0.09,2.0));float bloom=exp(-pow((radius-0.65)/0.19,2.0));float core=exp(-pow((radius-0.61)/0.014,2.0));gl_FragColor=vec4(vec3(0.50,0.87,1.0),halo*0.18+bloom*0.055+core*0.24);}');
  glare=plane('SelectionRearGlare',13,'void main(){vec2 point=effectUv-0.5;float radius=length(point);float beams=0.0;for(int index=0;index<7;index++){float axis=float(index)*0.8976+0.18+sin(time*0.45+float(index)*1.1)*0.24;vec2 direction=vec2(cos(axis),sin(axis));float along=dot(point,direction);float across=dot(point,vec2(-direction.y,direction.x));float width=0.0012+max(along,0.0)*0.004;float shaft=exp(-pow(across/width,2.0));float envelope=smoothstep(0.0,0.02,along)*(1.0-smoothstep(0.15,0.23,along));beams+=shaft*envelope*(0.45+0.55*pow(0.5+0.5*sin(time*0.85+float(index)*1.7),2.0));}gl_FragColor=vec4(vec3(0.66,0.89,1.0),min(beams,1.0)*0.85*smoothstep(0.134,0.139,length(point-vec2(0.0,0.0026))));}');
  const flareShader='void main(){vec2 point=effectUv-0.5;float haloRadius=length(point);float radius=haloRadius*(1.7/0.88);float angle=atan(point.y,point.x);float spike=0.045+0.39*pow(abs(cos(angle*4.0)),28.0);float rays=(1.0-smoothstep(spike*0.55,spike,radius))*(1.0-smoothstep(0.03,0.46,radius));float core=exp(-radius*radius*420.0);float halo=exp(-haloRadius*haloRadius*22.0)*0.28*(1.0-smoothstep(0.4,0.5,haloRadius));float pulse=0.35+0.65*pow(0.5+0.5*sin(time*1.3),2.0);gl_FragColor=vec4(vec3(0.83,0.96,1.0),(core+halo+rays*0.65)*pulse);}';
  const rear=plane('SelectionRearReflectionStar',1.7,flareShader);rear.position.set(1.12,1.20,-.65);rear.renderOrder=4;rear.material.depthTest=false;rearGlares.push(rear);
  surfaceGlares.push({x:-1.06,y:.83,size:195,phase:0},{x:.85,y:-.86,size:126,phase:2.1});
  const count=96,seeds=new Float32Array(count*3),sizes=new Float32Array(count),kinds=new Float32Array(count);for(let index=0;index<count;index++){seeds[index*3]=((index*0.61803398875)%1)*11-5.5;seeds[index*3+1]=(index*0.38196601125)%1;seeds[index*3+2]=((index*0.754877666)%1)*2-1;const variation=(index*0.41421356)%1;sizes[index]=(3+variation*5)*(0.55+((index*0.73205081)%1)*1.1);kinds[index]=index%3===0?0:1}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(seeds,3));geometry.setAttribute('pointSize',new THREE.BufferAttribute(sizes,1));geometry.setAttribute('pointKind',new THREE.BufferAttribute(kinds,1));
  const material=new THREE.ShaderMaterial({uniforms:{time:{value:0},pixelRatio:{value:renderer.getPixelRatio()},viewportScale:{value:1},particleScale:{value:2}},vertexShader:'uniform float time;uniform float pixelRatio;uniform float viewportScale;uniform float particleScale;attribute float pointSize;attribute float pointKind;varying float brightness;varying float kind;void main(){float phase=fract(position.y+time*(0.085+pointSize*0.003));vec3 point=vec3(position.x+sin(time*0.5+position.x)*0.08,5.4-phase*5.8,position.z+0.4);float impact=smoothstep(0.89,0.97,phase);brightness=smoothstep(0.0,0.06,phase)*(1.0-smoothstep(0.97,1.0,phase));kind=pointKind;vec4 projected=modelViewMatrix*vec4(point,1.0);gl_Position=projectionMatrix*projected;gl_PointSize=pointSize*particleScale*pixelRatio*viewportScale*(1.0+impact*3.5);}',fragmentShader:'varying float brightness;varying float kind;void main(){vec2 point=gl_PointCoord-0.5;float radius=length(point);float angle=atan(point.y,point.x);float core=exp(-radius*radius*65.0);float glow=exp(-radius*radius*18.0)*0.3;float tip=0.045+0.43*pow(abs(cos(angle*4.0)),24.0);float star=(1.0-smoothstep(tip*0.5,tip,radius))*(1.0-smoothstep(0.02,0.49,radius));float alpha=mix(core+glow,star+glow*0.3,kind);gl_FragColor=vec4(vec3(0.72,0.94,1.0),alpha*brightness*0.8);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});particles=new THREE.Points(geometry,material);particles.frustumCulled=false;particles.name='SelectionFallingLights';scene.add(particles);
  const haloMaterial=new THREE.ShaderMaterial({uniforms:material.uniforms,vertexShader:material.vertexShader.replace('gl_PointSize=pointSize','gl_PointSize=2.4*pointSize'),fragmentShader:'varying float brightness;void main(){float radius=length(gl_PointCoord-0.5);float halo=exp(-radius*radius*22.0)*(1.0-smoothstep(0.35,0.50,radius));gl_FragColor=vec4(vec3(0.48,0.83,1.0),halo*brightness*0.32);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});particleHalos=new THREE.Points(geometry,haloMaterial);particleHalos.frustumCulled=false;particleHalos.name='SelectionAirborneLightHalos';particleHalos.renderOrder=6;particles.renderOrder=7;scene.add(particleHalos);
 }
 function resize(){if(!camera)return;const fit=Math.min(innerWidth/1280,innerHeight/720),width=1280*fit,height=720*fit;renderer.setSize(width,height,false);Object.assign(renderer.domElement.style,{width:width+'px',height:height+'px',left:(innerWidth-width)/2+'px',top:(innerHeight-height)/2+'px'});camera.aspect=width/height;camera.updateProjectionMatrix();if(particles)particles.material.uniforms.viewportScale.value=fit}
 const ready=Promise.all([fetch(assetUrl('./Stage/Select/select-stage.json?v=select3d3')).then(response=>{if(!response.ok)throw Error('Select stage settings');return response.json()}),fetch(assetUrl('./Stage/Select/Select.glb.gz?v=select3d1')).then(response=>{if(!response.ok)throw Error('Select stage model');return new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()})]).then(async ([config,buffer])=>{settings=config;camera=new THREE.PerspectiveCamera(config.fov,16/9,.01,1000);camera.position.fromArray(config.cameraPosition);const model=await new GLTFLoader().parseAsync(buffer,'./');scene.add(model.scene);sphere=model.scene.getObjectByName(config.target);if(!sphere)model.scene.traverse(node=>{if(node.userData.name===config.target)sphere=node});if(!sphere)throw Error('Selection Sphere.004 missing');model.scene.traverse(node=>{if(!node.isMesh)return;for(const material of Array.isArray(node.material)?node.material:[node.material]){if(/^sky/i.test(node.name))material.depthWrite=false;if(node===sphere)material.side=THREE.FrontSide}});mixer=new THREE.AnimationMixer(model.scene);for(const clip of model.animations)mixer.clipAction(clip).play();addEffects();resize();render(0)});
 const center=new THREE.Vector3();
 function render(dt){if(!camera||!mixer)return;accumulator+=Math.max(0,dt);const steps=Math.floor((accumulator+1e-9)*30);if(!steps&&renderedFrames)return;const elapsed=steps/30;accumulator-=elapsed;time+=elapsed;mixer.update(elapsed);sphere.getWorldPosition(center);effects.position.copy(center);for(const mesh of [innerGlow,outerGlow,glare,...rearGlares]){mesh.quaternion.copy(camera.quaternion);mesh.material.uniforms.time.value=time}innerGlow.position.z=.12;innerGlow.renderOrder=10;outerGlow.position.z=.1;outerGlow.renderOrder=11;glare.position.z=-1.6;glare.renderOrder=5;glare.material.depthTest=false;particles.material.uniforms.time.value=time;renderer.render(scene,camera);renderedFrames++}
 function drawSurfaceGlares(context){if(!camera||!sphere)return;for(const flare of surfaceGlares){const point=center.clone().add(new THREE.Vector3(flare.x,flare.y,Math.sqrt(Math.max(0,1.4*1.4-flare.x*flare.x-flare.y*flare.y))+.04)).project(camera),x=(point.x+1)*640,y=(1-point.y)*360,pulse=.35+.65*Math.pow(.5+.5*Math.sin(time*1.3+flare.phase),2),radius=flare.size/2;context.save();context.translate(x,y);context.globalAlpha=pulse;context.globalCompositeOperation='lighter';const halo=context.createRadialGradient(0,0,0,0,0,radius*.95);halo.addColorStop(0,'rgba(255,255,255,0.95)');halo.addColorStop(.12,'rgba(210,245,255,0.65)');halo.addColorStop(1,'rgba(150,225,255,0)');context.fillStyle=halo;context.fillRect(-radius,-radius,radius*2,radius*2);context.beginPath();for(let index=0;index<16;index++){const angle=index*Math.PI/8-Math.PI/2,length=index%2?radius*.055:radius*(index%4===0?1:.65),pointX=Math.cos(angle)*length,pointY=Math.sin(angle)*length;if(!index)context.moveTo(pointX,pointY);else context.lineTo(pointX,pointY)}context.closePath();context.fillStyle='rgba(235,250,255,0.9)';context.fill();context.restore()}}
 window.addEventListener('resize',resize);
 return {ready,drawSurfaceGlares,render:dt=>{if(visible)render(dt)},setVisible:value=>{visible=value;if(!value)accumulator=0;renderer.domElement.hidden=!value},snapshot:()=>({loaded:!!mixer,visible,time,fps:30,renderedFrames,cameraPosition:camera?.position.toArray(),cameraBlender:settings?.cameraBlender,reflectionStars:surfaceGlares.length+rearGlares.length,particleScale:particles?.material.uniforms.particleScale.value,starParticles:particles?Array.from(particles.geometry.attributes.pointKind.array).filter(value=>value===1).length:0,beamAngle:Math.sin(time*.45)*.24,glowTarget:settings?.target,innerGlow:!!innerGlow,outerGlow:!!outerGlow,glare:!!glare,fallingLights:particles?.geometry.attributes.position.count||0,animations:settings?.animations})};
}
