import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {assetUrl} from '../../Engine/asset-paths.js?v=02362';

export function createSelectStage(parent){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.id='selectStage3D';renderer.domElement.style.cssText='position:absolute;pointer-events:none';parent.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x061b40);scene.add(new THREE.HemisphereLight(0xd9faff,0x3977be,2));
 let camera,mixer,sphere,settings,visible=false,time=0,innerGlow,outerGlow,glare,particles;
 const effects=new THREE.Group();scene.add(effects);
 const vertexShader='varying vec2 effectUv;void main(){effectUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}';
 function plane(name,size,fragmentShader){const material=new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader,fragmentShader:'uniform float time;varying vec2 effectUv;'+fragmentShader,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,depthTest:true,toneMapped:false});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(size,size),material);mesh.name=name;effects.add(mesh);return mesh}
 function addEffects(){
  innerGlow=plane('SelectionInnerGlow',3.5,'void main(){float radius=length(effectUv-0.5)*2.0;float edge=exp(-pow((radius-0.78)/0.065,2.0));float inside=exp(-pow((radius-0.70)/0.12,2.0))*(1.0-smoothstep(0.70,0.90,radius));float pulse=0.93+0.07*sin(time*1.4);gl_FragColor=vec4(vec3(0.58,0.92,1.0),(edge*0.32+inside*0.15)*pulse);}');
  outerGlow=plane('SelectionOuterGlow',4.6,'void main(){float radius=length(effectUv-0.5)*2.0;float halo=exp(-pow((radius-0.62)/0.09,2.0));float bloom=exp(-pow((radius-0.65)/0.19,2.0));float core=exp(-pow((radius-0.61)/0.014,2.0));gl_FragColor=vec4(vec3(0.50,0.87,1.0),halo*0.18+bloom*0.055+core*0.24);}');
  glare=plane('SelectionRearGlare',10,'void main(){vec2 point=effectUv-0.5;float radius=length(point);float angle=atan(point.y,point.x);float beams=0.0;for(int index=0;index<7;index++){float axis=float(index)*0.8976+0.18+sin(time*0.13+float(index))*0.025;float alignment=cos(angle-axis);beams+=pow(max(alignment,0.0),95.0)*(0.65+0.35*sin(time*0.7+float(index)*1.7));}float envelope=smoothstep(0.18,0.22,radius)*(1.0-smoothstep(0.28,0.50,radius));gl_FragColor=vec4(vec3(0.47,0.79,1.0),beams*envelope*0.48);}');
  const count=96,seeds=new Float32Array(count*3),sizes=new Float32Array(count);for(let index=0;index<count;index++){seeds[index*3]=((index*0.61803398875)%1)*11-5.5;seeds[index*3+1]=(index*0.38196601125)%1;seeds[index*3+2]=((index*0.754877666)%1)*2-1;sizes[index]=3+((index*0.41421356)%1)*5}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(seeds,3));geometry.setAttribute('pointSize',new THREE.BufferAttribute(sizes,1));
  const material=new THREE.ShaderMaterial({uniforms:{time:{value:0},pixelRatio:{value:renderer.getPixelRatio()}},vertexShader:'uniform float time;uniform float pixelRatio;attribute float pointSize;varying float brightness;void main(){float phase=fract(position.y+time*(0.085+pointSize*0.003));vec3 point=vec3(position.x+sin(time*0.5+position.x)*0.08,5.4-phase*5.8,position.z+0.4);float impact=smoothstep(0.89,0.97,phase);brightness=smoothstep(0.0,0.06,phase)*(1.0-smoothstep(0.97,1.0,phase));vec4 projected=modelViewMatrix*vec4(point,1.0);gl_Position=projectionMatrix*projected;gl_PointSize=pointSize*pixelRatio*(1.0+impact*3.5);}',fragmentShader:'varying float brightness;void main(){vec2 point=gl_PointCoord-0.5;float radius=length(point);float core=exp(-radius*radius*65.0);float glow=exp(-radius*radius*18.0)*0.3;float cross=exp(-abs(point.x)*65.0)*exp(-abs(point.y)*8.0)+exp(-abs(point.y)*65.0)*exp(-abs(point.x)*8.0);gl_FragColor=vec4(vec3(0.72,0.94,1.0),(core+glow+cross*0.15)*brightness*0.8);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});particles=new THREE.Points(geometry,material);particles.frustumCulled=false;particles.name='SelectionFallingLights';scene.add(particles);
 }
 function resize(){if(!camera)return;const fit=Math.min(innerWidth/1280,innerHeight/720),width=1280*fit,height=720*fit;renderer.setSize(width,height,false);Object.assign(renderer.domElement.style,{width:width+'px',height:height+'px',left:(innerWidth-width)/2+'px',top:(innerHeight-height)/2+'px'});camera.aspect=width/height;camera.updateProjectionMatrix()}
 const ready=Promise.all([fetch(assetUrl('./Stage/Select/select-stage.json?v=select3d1')).then(response=>{if(!response.ok)throw Error('Select stage settings');return response.json()}),fetch(assetUrl('./Stage/Select/Select.glb.gz?v=select3d1')).then(response=>{if(!response.ok)throw Error('Select stage model');return new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()})]).then(async ([config,buffer])=>{settings=config;camera=new THREE.PerspectiveCamera(config.fov,16/9,.01,1000);camera.position.fromArray(config.cameraPosition);const model=await new GLTFLoader().parseAsync(buffer,'./');scene.add(model.scene);sphere=model.scene.getObjectByName(config.target);if(!sphere)model.scene.traverse(node=>{if(node.userData.name===config.target)sphere=node});if(!sphere)throw Error('Selection Sphere.004 missing');model.scene.traverse(node=>{if(!node.isMesh)return;for(const material of Array.isArray(node.material)?node.material:[node.material]){if(/^sky/i.test(node.name))material.depthWrite=false;if(node===sphere)material.side=THREE.FrontSide}});mixer=new THREE.AnimationMixer(model.scene);for(const clip of model.animations)mixer.clipAction(clip).play();addEffects();resize();render(0)});
 const center=new THREE.Vector3();
 function render(dt){if(!camera||!mixer)return;time+=Math.min(dt,.05);mixer.update(Math.min(dt,.05));sphere.getWorldPosition(center);effects.position.copy(center);for(const mesh of [innerGlow,outerGlow,glare]){mesh.quaternion.copy(camera.quaternion);mesh.material.uniforms.time.value=time}innerGlow.position.z=.12;innerGlow.renderOrder=10;outerGlow.position.z=.1;outerGlow.renderOrder=11;glare.position.z=-1.6;glare.renderOrder=5;glare.material.depthTest=false;particles.material.uniforms.time.value=time;renderer.render(scene,camera)}
 window.addEventListener('resize',resize);
 return {ready,render:dt=>{if(visible)render(dt)},setVisible:value=>{visible=value;renderer.domElement.hidden=!value},snapshot:()=>({loaded:!!mixer,visible,time,glowTarget:settings?.target,innerGlow:!!innerGlow,outerGlow:!!outerGlow,glare:!!glare,fallingLights:particles?.geometry.attributes.position.count||0,animations:settings?.animations})};
}
