import {abilityKeys,abilityBudget,abilityProfile,changeAbility} from './ability-system.js?v=acs1';
export function createAcsScreen(parent,api){
 const view=document.createElement('section');view.id='abilityCustomize';view.hidden=true;view.style.cssText='position:absolute;inset:0;background:#05050d;z-index:4';parent.appendChild(view);
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';view.appendChild(canvas);const context=canvas.getContext('2d');
 const controls=document.createElement('div');controls.style.cssText='position:absolute;width:1280px;height:720px;transform-origin:top left';view.appendChild(controls);
 const style=document.createElement('style');style.textContent='@font-face{font-family:BlackQuality;src:url("./Data/ACS/BlackQuality.ttf")}';view.appendChild(style);
 const layout={portraitCenters:[319,961],nameCenters:[319,961],groupCenters:[860,420]};
 const images={};let manifest,settings,choice,mode,player=0,cursor=0,points=[Array(6).fill(0),Array(6).fill(0)],age=0,lastTime,loaded=false,error,fromSide=0,transitionStart=-30,entrySerial=0;
 const lights=Array.from({length:100},()=>({x:Math.random()*1280,phase:Math.random(),speed:3+Math.random()*3,size:2+Math.random()*7,inset:20+Math.random()*40,star:Math.random()<.4}));
 const ready=Promise.all([fetch('./Data/Select/select-screen.json?v=acs1').then(response=>{if(!response.ok)throw Error('ACS placement settings');return response.json()}).then(data=>settings=data.settings),fetch('./Data/Select/selection-assets.json?v=acs1').then(response=>{if(!response.ok)throw Error('ACS character manifest');return response.json()}).then(data=>manifest=data),...['ACS','ACS Title','Mark','0','1','2','3','4','5'].map(async key=>{const image=new Image();image.src='./Data/ACS/'+encodeURIComponent(key)+'.webp';await image.decode();images[key]=image}),Promise.resolve().then(async()=>{const image=new Image();image.src='./Stage/Select/background.webp?v=selection8';await image.decode();images.background=image})]).catch(reason=>{error=reason;throw reason});
 function remaining(){return abilityBudget(mode)-points[player].reduce((total,value)=>total+value,0)}
 function mirrorAmount(){const progress=Math.min(1,Math.max(0,(age-transitionStart)/30)),ease=1-(1-progress)**3;return fromSide+(player-fromSide)*ease}
 function transitioning(){return age-transitionStart<30}
 function skillPoint(index,radius=215){const angle=-Math.PI/2+index*Math.PI/3;return {x:layout.groupCenters[0]+(layout.groupCenters[1]-layout.groupCenters[0])*mirrorAmount()+Math.cos(angle)*radius,y:370+Math.sin(angle)*radius}}
 function button(label,handler,x,y,width,height){const element=document.createElement('button');element.type='button';element.setAttribute('aria-label',label);element.style.cssText=`position:absolute;left:${x}px;top:${y}px;width:${width}px;height:${height}px;background:transparent;border:0;padding:0;box-sizing:border-box;line-height:0;color:white;touch-action:manipulation`;element.addEventListener('click',handler);controls.appendChild(element);return element}
 function update(){controls.replaceChildren();for(let index=0;index<6;index++){const point=skillPoint(index,185),element=button(abilityKeys[index],()=>{cursor=index;change(1)},point.x-55,point.y-45,110,90);element.dataset.ability=abilityKeys[index];element.title=abilityKeys[index]+': '+points[player][index]}
 const confirm=button('Confirm abilities',confirmPlayer,787,662-images.confirm.naturalHeight/2,images.confirm.naturalWidth,images.confirm.naturalHeight);confirm.id='confirmAbilities';if(images.confirm){const image=document.createElement('img');image.src=images.confirm.src;image.style.cssText='display:block;width:100%;height:100%;object-fit:contain;pointer-events:none';confirm.appendChild(image)}else confirm.textContent='CONFIRM';confirm.addEventListener('pointerdown',()=>confirm.style.transform='scale(.9)');for(const event of ['pointerup','pointercancel','pointerleave'])confirm.addEventListener(event,()=>confirm.style.transform='');const back=button('Previous player',backPlayer,20,20,100,36);back.textContent='BACK';back.style.background='#0a163be8';back.style.border='1px solid #e4ca81';positionControls();resize()}
 function change(direction){if(transitioning())return;points[player]=changeAbility(points[player],cursor,direction,abilityBudget(mode));update()}
 function confirmPlayer(){if(age<30||transitioning())return;if(player===0){fromSide=0;player=1;cursor=0;transitionStart=age;update()}else{const allocation=points.map(values=>[...values]);hide();api.confirm(mode,{...choice,acs:allocation})}}
 function backPlayer(){if(transitioning())return;if(player){fromSide=1;player=0;transitionStart=age;update()}else{hide();api.back(mode)}}
 async function loadCharacterAssets(){for(const identifier of Object.keys(manifest.characters)){const entry=manifest.characters[identifier];for(const kind of ['portrait','name']){const item=entry[kind];if(!item)continue;if(images[identifier+kind])continue;const image=new Image();image.src='./'+item.file+'?v=acs1';await image.decode();images[identifier+kind]=image}}const image=new Image();image.src='./'+manifest.buttons.confirm.file+'?v=acs1';await image.decode();images.confirm=image}
 const prepared=ready.then(async()=>{await loadCharacterAssets();await document.fonts.load('60px BlackQuality')});
 async function show(next,nextChoice){const serial=++entrySerial;try{await prepared;if(serial!==entrySerial)return;mode=next;choice=nextChoice;player=0;fromSide=0;transitionStart=-30;cursor=0;points=[Array(6).fill(0),Array(6).fill(0)];loaded=true;age=0;lastTime=undefined;view.hidden=false;update()}catch(reason){error=reason;api.error?.(reason)}}
 function hide(){entrySerial++;view.hidden=true;lastTime=undefined}
 function positionControls(){const mirror=mirrorAmount();for(const [index,element] of [...controls.querySelectorAll('[data-ability]')].entries()){const point=skillPoint(index,185);element.style.left=point.x-55+'px';element.disabled=transitioning()}const confirm=controls.querySelector('#confirmAbilities');if(confirm){confirm.style.left=(player?1280-787-images.confirm.naturalWidth:787)+'px';confirm.style.opacity=transitioning()?'0':'1';confirm.disabled=transitioning()}}
 function drawPointPools(){const mirror=mirrorAmount();for(const target of [0,1]){context.save();context.globalAlpha=target===0?1-mirror:mirror;const remaining=abilityBudget(mode)-points[target].reduce((total,value)=>total+value,0);text(remaining,target?529:695,675,60);text('pt',target?585:751,675,40);if(transitioning())context.drawImage(images.confirm,target?1280-787-images.confirm.naturalWidth:787,662-images.confirm.naturalHeight/2,images.confirm.naturalWidth,images.confirm.naturalHeight);context.restore()}}
 function resize(){const fit=Math.min(innerWidth/1280,innerHeight/720);Object.assign(controls.style,{left:(innerWidth-1280*fit)/2+'px',top:(innerHeight-720*fit)/2+'px',transform:'scale('+fit+')'});draw()}
 function text(value,x,y,size,color='white'){context.save();context.translate(x,y);context.scale(1.25,1);context.font=size+'px BlackQuality,serif';if(color==='glow'){context.shadowColor='white';context.shadowBlur=14;color='white'}context.fillStyle=color;context.textAlign='center';context.fillText(value,0,0);context.restore()}
 function draw(){if(view.hidden)return;const fit=Math.min(innerWidth/1280,innerHeight/720);canvas.width=Math.round(innerWidth*devicePixelRatio);canvas.height=Math.round(innerHeight*devicePixelRatio);context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);context.fillStyle='#05050d';context.fillRect(0,0,innerWidth,innerHeight);context.translate((innerWidth-1280*fit)/2,(innerHeight-720*fit)/2);context.scale(fit,fit);context.beginPath();context.rect(0,0,1280,720);context.clip();if(!loaded){text(error?'Unable to load ACS':'Loading…',640,360,30);return}context.drawImage(images.background,0,0,1280,720);
 for(const light of lights){const phase=(age/60/light.speed+light.phase)%1,travel=Math.min(1,phase/.7),land=720-light.inset,y=-40+(land+40)*travel,alpha=phase>.85?(1-phase)/.15:Math.min(1,phase/.08),radius=light.size*(phase>.7?1+(phase-.7)*5:1);const glow=context.createRadialGradient(light.x,y,0,light.x,y,radius*3);glow.addColorStop(0,`rgba(190,245,255,${alpha*.6})`);glow.addColorStop(1,'rgba(150,220,255,0)');context.fillStyle=glow;context.fillRect(light.x-radius*3,y-radius*3,radius*6,radius*6);context.fillStyle=`rgba(235,255,255,${alpha})`;if(light.star){context.beginPath();for(let tip=0;tip<16;tip++){const angle=tip*Math.PI/8,length=tip%2?light.size*.1:light.size;const x=light.x+Math.cos(angle)*length,vertical=y+Math.sin(angle)*length;if(!tip)context.moveTo(x,vertical);else context.lineTo(x,vertical)}context.closePath();context.fill()}else{context.beginPath();context.arc(light.x,y,light.size/3,0,Math.PI*2);context.fill()}}
 const progress=Math.min(1,age/30),ease=1-(1-progress)**3,mirror=mirrorAmount();for(const target of [0,1]){const identifier=choice.players[target],entry=manifest.characters[identifier],portrait=entry.portrait,name=entry.name;context.save();context.globalAlpha=target===0?1-mirror:player===0&&!transitioning()?1-ease:mirror;const p1Anchor=layout.portraitCenters[0]-100,p2Anchor=Number(settings['p2.face.offset'].split(',')[0]),anchor=target===0?p1Anchor+100*ease:layout.portraitCenters[1]+(1-mirror)*400;const portraitX=anchor-portrait.w/2;context.drawImage(images[identifier+'portrait'],target===1&&player===0&&!transitioning()?p2Anchor+portrait.x-640:portraitX,portrait.y,portrait.w,portrait.h);context.drawImage(images[identifier+'name'],(target===1&&player===0&&!transitioning()?p2Anchor:anchor)-name.w/2,580+(52.5-name.h)/2,name.w,name.h);context.restore()}
 context.drawImage(images['ACS Title'],350,-181+168*ease,603,181);context.save();context.globalAlpha=ease;const shift=300*(1-ease);context.drawImage(images.ACS,layout.groupCenters[0]+(layout.groupCenters[1]-layout.groupCenters[0])*mirrorAmount()-180+shift,190,360,360);context.drawImage(images.Mark,layout.groupCenters[0]+(layout.groupCenters[1]-layout.groupCenters[0])*mirrorAmount()-425.4/2+shift,370-441/2,425.4,441);context.translate(shift,0);context.beginPath();for(let index=0;index<6;index++){const point=skillPoint(index,27.5+points[player][index]*22);if(!index)context.moveTo(point.x,point.y);else context.lineTo(point.x,point.y)}context.closePath();context.fillStyle='rgba(110,125,255,.5)';context.fill();context.strokeStyle='#c4d4ff';context.lineWidth=2;context.stroke();for(let index=0;index<6;index++){const point=skillPoint(index,152);text(points[player][index],point.x,point.y+10,28.8,index===cursor?'glow':'#603e13');}context.restore();drawPointPools()}
 function handleKey(event){if(view.hidden)return false;if(!loaded||transitioning())return true;if(event.repeat)return true;const code=event.code;if(['ArrowRight','ArrowDown'].includes(code)){cursor=(cursor+1)%6;update()}else if(['ArrowLeft','ArrowUp'].includes(code)){cursor=(cursor+5)%6;update()}else if(['KeyZ','KeyA','Numpad1','Numpad0'].includes(code))change(1);else if(['KeyX','KeyS','Numpad2','NumpadDecimal'].includes(code))change(-1);else if(code==='Enter')confirmPlayer();else if(code==='Escape')backPlayer();return true}
 function animate(time){if(!view.hidden){if(lastTime!==undefined&&loaded)age+=Math.min((time-lastTime)/1000,.05)*60;lastTime=time;positionControls();draw()}requestAnimationFrame(animate)}requestAnimationFrame(animate);window.addEventListener('resize',resize);
 return {ready:prepared,show,hide,handleKey,snapshot:()=>({visible:!view.hidden,loaded,player,cursor,points:points.map(values=>[...values]),remaining:remaining(),mirror:mirrorAmount(),layout:{portraitCenters:layout.portraitCenters,nameCenters:layout.nameCenters,groupCenter:860-440*mirrorAmount(),confirmSize:images.confirm?[images.confirm.naturalWidth,images.confirm.naturalHeight]:null},transitioning:transitioning(),titleY:-181+168*(1-(1-Math.min(1,age/30))**3),profiles:points.map(abilityProfile)})};
}

