import {abilityKeys,abilityBudget,abilityProfile,changeAbility} from './ability-system.js?v=acs1';
export function createAcsScreen(parent,api){
 const view=document.createElement('section');view.id='abilityCustomize';view.hidden=true;view.style.cssText='position:absolute;inset:0;background:#05050d;z-index:4';parent.appendChild(view);
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';view.appendChild(canvas);const context=canvas.getContext('2d');
 const controls=document.createElement('div');controls.style.cssText='position:absolute;width:1280px;height:720px;transform-origin:top left';view.appendChild(controls);
 const style=document.createElement('style');style.textContent='@font-face{font-family:BlackQuality;src:url("./Data/ACS/BlackQuality.ttf")}';view.appendChild(style);
 const images={};let manifest,settings,choice,mode,player=0,cursor=0,points=[Array(6).fill(0),Array(6).fill(0)],age=0,lastTime,loaded=false,error;
 const lights=Array.from({length:100},()=>({x:Math.random()*1280,phase:Math.random(),speed:3+Math.random()*3,size:2+Math.random()*7,inset:20+Math.random()*40,star:Math.random()<.4}));
 const ready=Promise.all([fetch('./Data/Select/select-screen.json?v=acs1').then(response=>{if(!response.ok)throw Error('ACS placement settings');return response.json()}).then(data=>settings=data.settings),fetch('./Data/Select/selection-assets.json?v=acs1').then(response=>{if(!response.ok)throw Error('ACS character manifest');return response.json()}).then(data=>manifest=data),...['ACS','ACS Title','Mark','0','1','2','3','4','5'].map(async key=>{const image=new Image();image.src='./Data/ACS/'+encodeURIComponent(key)+'.webp';await image.decode();images[key]=image}),Promise.resolve().then(async()=>{const image=new Image();image.src='./Stage/Select/background.webp?v=selection8';await image.decode();images.background=image})]).catch(reason=>{error=reason;throw reason});
 function remaining(){return abilityBudget(mode)-points[player].reduce((total,value)=>total+value,0)}
 function skillPoint(index,radius=215){const angle=-Math.PI/2+index*Math.PI/3;return {x:860+Math.cos(angle)*radius,y:370+Math.sin(angle)*radius}}
 function button(label,handler,x,y,width,height){const element=document.createElement('button');element.type='button';element.setAttribute('aria-label',label);element.style.cssText=`position:absolute;left:${x}px;top:${y}px;width:${width}px;height:${height}px;background:transparent;border:0;color:white;touch-action:manipulation`;element.addEventListener('click',handler);controls.appendChild(element);return element}
 function update(){controls.replaceChildren();for(let index=0;index<6;index++){const point=skillPoint(index,185),element=button(abilityKeys[index],()=>{cursor=index;change(1)},point.x-55,point.y-45,110,90);element.dataset.ability=abilityKeys[index];element.title=abilityKeys[index]+': '+points[player][index]}
 const confirm=button('Confirm abilities',confirmPlayer,787,632,265,64);confirm.id='confirmAbilities';if(images.confirm){const image=document.createElement('img');image.src=images.confirm.src;image.style.cssText='width:100%;height:100%;pointer-events:none';confirm.appendChild(image)}else confirm.textContent='CONFIRM';confirm.addEventListener('pointerdown',()=>confirm.style.transform='scale(.9)');for(const event of ['pointerup','pointercancel','pointerleave'])confirm.addEventListener(event,()=>confirm.style.transform='');const back=button('Previous player',backPlayer,20,20,100,36);back.textContent='BACK';back.style.background='#0a163be8';back.style.border='1px solid #e4ca81';resize()}
 function change(direction){points[player]=changeAbility(points[player],cursor,direction,abilityBudget(mode));update()}
 function confirmPlayer(){if(age<30)return;if(player===0){player=1;cursor=0;age=0;update()}else{const allocation=points.map(values=>[...values]);hide();api.confirm(mode,{...choice,acs:allocation})}}
 function backPlayer(){if(player){player=0;age=0;update()}else{hide();api.back(mode)}}
 async function loadCharacterAssets(){for(const identifier of new Set(choice.players)){const entry=manifest.characters[identifier];for(const kind of ['portrait','name']){const item=entry[kind],image=new Image();image.src='./'+item.file+'?v=acs1';await image.decode();images[identifier+kind]=image}}const image=new Image();image.src='./'+manifest.buttons.confirm.file+'?v=acs1';await image.decode();images.confirm=image}
 async function show(next,nextChoice){mode=next;choice=nextChoice;player=0;cursor=0;points=[Array(6).fill(0),Array(6).fill(0)];view.hidden=false;loaded=false;age=0;lastTime=undefined;controls.replaceChildren();try{await ready;await loadCharacterAssets();await document.fonts.load('60px BlackQuality');loaded=true;age=0;update()}catch(reason){error=reason;draw()}}
 function hide(){view.hidden=true;lastTime=undefined}
 function resize(){const fit=Math.min(innerWidth/1280,innerHeight/720);Object.assign(controls.style,{left:(innerWidth-1280*fit)/2+'px',top:(innerHeight-720*fit)/2+'px',transform:'scale('+fit+')'});draw()}
 function text(value,x,y,size,color='white'){context.save();context.translate(x,y);context.scale(1.25,1);context.font=size+'px BlackQuality,serif';context.fillStyle=color;context.textAlign='center';context.fillText(value,0,0);context.restore()}
 function draw(){if(view.hidden)return;const fit=Math.min(innerWidth/1280,innerHeight/720);canvas.width=Math.round(innerWidth*devicePixelRatio);canvas.height=Math.round(innerHeight*devicePixelRatio);context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);context.fillStyle='#05050d';context.fillRect(0,0,innerWidth,innerHeight);context.translate((innerWidth-1280*fit)/2,(innerHeight-720*fit)/2);context.scale(fit,fit);context.beginPath();context.rect(0,0,1280,720);context.clip();if(!loaded){text(error?'Unable to load ACS':'Loading…',640,360,30);return}context.drawImage(images.background,0,0,1280,720);
 for(const light of lights){const phase=(age/60/light.speed+light.phase)%1,travel=Math.min(1,phase/.7),land=720-light.inset,y=-40+(land+40)*travel,alpha=phase>.85?(1-phase)/.15:Math.min(1,phase/.08),radius=light.size*(phase>.7?1+(phase-.7)*5:1);const glow=context.createRadialGradient(light.x,y,0,light.x,y,radius*3);glow.addColorStop(0,`rgba(190,245,255,${alpha*.6})`);glow.addColorStop(1,'rgba(150,220,255,0)');context.fillStyle=glow;context.fillRect(light.x-radius*3,y-radius*3,radius*6,radius*6);context.fillStyle=`rgba(235,255,255,${alpha})`;if(light.star){context.beginPath();for(let tip=0;tip<16;tip++){const angle=tip*Math.PI/8,length=tip%2?light.size*.1:light.size;const x=light.x+Math.cos(angle)*length,vertical=y+Math.sin(angle)*length;if(!tip)context.moveTo(x,vertical);else context.lineTo(x,vertical)}context.closePath();context.fill()}else{context.beginPath();context.arc(light.x,y,light.size/3,0,Math.PI*2);context.fill()}}
 const progress=Math.min(1,age/30),ease=1-(1-progress)**3;for(const target of player===0?[0,1]:[1]){const identifier=choice.players[target],entry=manifest.characters[identifier],portrait=entry.portrait,name=entry.name;context.save();context.globalAlpha=player===0&&target===1?1-ease:1;const anchor=Number(settings[target===1&&player===0?'p2.face.offset':'p1.face.offset'].split(',')[0]),offset=target===1&&player===0?0:100*ease;context.drawImage(images[identifier+'portrait'],anchor+portrait.x-640+offset,portrait.y,portrait.w,portrait.h);context.drawImage(images[identifier+'name'],anchor+offset-name.w/2,580+(52.5-name.h)/2,name.w,name.h);context.restore()}
 context.drawImage(images['ACS Title'],350,-181+168*ease,603,181);context.save();context.globalAlpha=ease;const shift=300*(1-ease);context.drawImage(images.ACS,680+shift,190,360,360);context.drawImage(images.Mark,650+shift,150,425.4,441);context.translate(shift,0);context.beginPath();for(let index=0;index<6;index++){const point=skillPoint(index,points[player][index]*27.5);if(!index)context.moveTo(point.x,point.y);else context.lineTo(point.x,point.y)}context.closePath();context.fillStyle='rgba(110,125,255,.5)';context.fill();context.strokeStyle='#c4d4ff';context.lineWidth=2;context.stroke();for(let index=0;index<6;index++){const point=skillPoint(index,152);text(points[player][index],point.x,point.y+10,28.8,'#603e13');if(index===cursor){context.strokeStyle='white';context.lineWidth=2;context.beginPath();context.arc(point.x,point.y,25,0,Math.PI*2);context.stroke()}}context.restore();text(remaining(),695,675,60);text('pt',751,675,40)}
 function handleKey(event){if(view.hidden)return false;if(!loaded)return true;if(event.repeat)return true;const code=event.code;if(['ArrowRight','ArrowDown'].includes(code)){cursor=(cursor+1)%6;update()}else if(['ArrowLeft','ArrowUp'].includes(code)){cursor=(cursor+5)%6;update()}else if(['KeyZ','KeyA','Numpad1','Numpad0'].includes(code))change(1);else if(['KeyX','KeyS','Numpad2','NumpadDecimal'].includes(code))change(-1);else if(code==='Enter')confirmPlayer();else if(code==='Escape')backPlayer();return true}
 function animate(time){if(!view.hidden){if(lastTime!==undefined&&loaded)age+=Math.min((time-lastTime)/1000,.05)*60;lastTime=time;draw()}requestAnimationFrame(animate)}requestAnimationFrame(animate);window.addEventListener('resize',resize);
 return {ready,show,hide,handleKey,snapshot:()=>({visible:!view.hidden,loaded,player,cursor,points:points.map(values=>[...values]),remaining:remaining(),profiles:points.map(abilityProfile)})};
}

