import {createDeclarationFlow} from './declaration-flow.js?v=declaration5';
export function createDeclarationScreen(api){
 let manifest,variants=[],active=false,currentAudio=null,serial=0;const images=new Map(),audio=new Map();
 const ready=fetch('./Data/VS/declarations.json?v=declaration5').then(response=>{if(!response.ok)throw Error('Declaration manifest');return response.json()}).then(async data=>{manifest=data;for(const character of Object.values(data.characters))for(const variant of [...character.variants,...character.winVariants||[],...character.loseVariants||[]]){if(!images.has(variant.image)){const image=new Image();image.src='./'+variant.image;await image.decode();images.set(variant.image,image)}for(const cue of variant.cues)if(!audio.has(cue.file)){const response=await fetch('./'+cue.file);if(!response.ok)throw Error('Declaration voice '+cue.file);const blob=await response.blob();const source=new Audio(URL.createObjectURL(blob));audio.set(cue.file,source)}}});
 const flow=createDeclarationFlow({variant:player=>variants[player-1],playing:()=>!!currentAudio&&!currentAudio.ended&&!currentAudio.paused,play:(player,cue)=>{currentAudio?.pause();const source=audio.get(cue.file),clip=api.sound(source.cloneNode());currentAudio=clip;clip.play().catch(error=>{api.error?.(error)})},complete:()=>{active=false;api.complete()}});
 function begin(players,options={}){variants=players.map((identifier,index)=>{const character=manifest.characters[identifier],available=options.result?(options.winner===index+1?character?.winVariants:character?.loseVariants):character?.variants;if(!available?.length)throw Error('Declaration variant missing for '+identifier);return available[Math.floor(Math.random()*available.length)]});active=true;serial++;flow.begin(options);api.start?.()}
 function reset(){serial++;active=false;currentAudio?.pause();currentAudio=null;flow.reset()}
 function draw(context){if(!active&&flow.snapshot().phase!=='done')return;const {ticks,result,winner,movement,loserOpacity}=flow.snapshot(),progress=Math.min(1,ticks/90),ease=1-(1-progress)**3;for(const [index,variant] of variants.entries()){const image=images.get(variant.image),height=360,width=image.naturalWidth/image.naturalHeight*height,center=index?1000+(1-ease)*450:280-(1-ease)*450,vertical=360+(result&&winner?(index+1===winner?-60:60)*movement:0);context.save();context.globalAlpha*=progress*(result&&winner&&index+1!==winner?loserOpacity:1);context.drawImage(image,center-width/2,vertical-height/2,width,height);context.restore()}const fade=flow.fade();if(fade){context.save();context.globalAlpha=fade;context.fillStyle='black';context.fillRect(0,0,1280,720);context.restore()}}
 return {ready,begin,reset,draw,step:()=>{if(active)flow.step()},opacity:flow.acsOpacity,active:()=>active,snapshot:()=>({...flow.snapshot(),active,variants:variants.map(variant=>variant.id)})};
}

