import {letterBouncePose} from './letter-animation.js?v=02372';

let assetsPromise;
export function preloadLoadingAssets(){
 if(!assetsPromise)assetsPromise=fetch(new URL('../Data/Loading/loading-atlas.json?v=02372',import.meta.url)).then(response=>{if(!response.ok)throw Error('Loading artwork HTTP '+response.status);return response.json()}).then(async config=>{const image=new Image();image.src=new URL('../Data/Loading/'+config.atlas+'?v=02372',import.meta.url).href;await image.decode();const atlas=await createImageBitmap(image),staging=document.createElement('canvas');staging.width=config.size[0];staging.height=config.size[1];staging.getContext('2d').drawImage(atlas,0,0);return {config,atlas}});
 return assetsPromise;
}

export function loadingLetterPose(tick,index,duration=58){return letterBouncePose(tick-index*duration,duration)}

export function createLoadingScreen(parent=document.body,id='palaceLoading'){
 const view=document.createElement('section');view.id=id;view.hidden=true;view.style.cssText='position:fixed;inset:0;z-index:90;background:#000;color:#fff;display:none;touch-action:none';view.setAttribute('aria-label','Loading');view.setAttribute('aria-busy','true');
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';view.appendChild(canvas);const context=canvas.getContext('2d');
 const content=document.createElement('div');content.style.cssText='position:absolute;width:1280px;height:720px;transform-origin:0 0;pointer-events:none';view.appendChild(content);
 const label=document.createElement('div');label.textContent='NOW LOADING';label.setAttribute('role','status');content.appendChild(label);
 const bar=document.createElement('div');bar.style.cssText='position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)';bar.setAttribute('role','progressbar');bar.setAttribute('aria-label','Loading progress');bar.setAttribute('aria-valuemin','0');bar.setAttribute('aria-valuemax','100');content.appendChild(bar);
 const fill=document.createElement('div');fill.style.cssText='height:100%;width:0%;background:#FF3EA7';bar.appendChild(fill);
 const percentage=document.createElement('div');percentage.style.cssText='position:absolute;left:640px;top:520px;transform:translateX(-50%);font:16px system-ui;color:white';percentage.setAttribute('aria-hidden','true');content.appendChild(percentage);
 const exit=document.createElement('button');exit.textContent='返回';exit.hidden=true;exit.style.cssText='position:absolute;left:640px;top:600px;transform:translateX(-50%);border:1px solid #777;background:#000;color:#fff;padding:8px 20px;pointer-events:auto';content.appendChild(exit);
 const testControls=document.createElement('div');testControls.hidden=true;testControls.style.cssText='position:absolute;right:20px;top:20px;pointer-events:auto';content.appendChild(testControls);
 const reload=document.createElement('button');reload.id=id+'Reload';reload.textContent='重新載入';reload.style.cssText='display:block;width:150px;margin-bottom:10px;padding:9px;border:1px solid #ff3ea7;border-radius:6px;background:#15101b;color:white;font:16px system-ui';testControls.appendChild(reload);
 const confirm=document.createElement('button');confirm.id=id+'Confirm';confirm.textContent='確定';confirm.style.cssText=reload.style.cssText;testControls.appendChild(confirm);parent.appendChild(view);
 let assets,progress=0,tick=0,lastFrame,animationFrame,test=false,onExit;
 const ready=preloadLoadingAssets().then(value=>{assets=value;if(!view.hidden)render();return value});ready.catch(error=>{if(!view.hidden)fail(error)});
 function resize(){const ratio=devicePixelRatio||1,width=Math.round(innerWidth*ratio),height=Math.round(innerHeight*ratio);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}const scale=Math.min(innerWidth/1280,innerHeight/720),left=(innerWidth-1280*scale)/2,top=(innerHeight-720*scale)/2;content.style.left=left+'px';content.style.top=top+'px';content.style.transform='scale('+scale+')';context.setTransform(ratio,0,0,ratio,0,0);context.fillStyle='#000';context.fillRect(0,0,innerWidth,innerHeight);context.translate(left,top);context.scale(scale,scale)}
 function sprite(name,x,y,scale=1){const entry=assets.config.sprites[name];context.drawImage(assets.atlas,entry.x,entry.y,entry.w,entry.h,x-entry.originalSize[0]*scale/2+entry.crop[0]*scale,y-entry.originalSize[1]*scale/2+entry.crop[1]*scale,entry.w*scale,entry.h*scale)}
 function render(atTick=tick){resize();if(!assets)return;const config=assets.config;context.save();context.beginPath();context.rect(0,0,1280,720);context.clip();const luna=config.luna,frame=luna.frames[Math.floor(atTick/luna.frameTicks)%luna.frames.length],lunaSprite=config.sprites[frame];sprite(frame,luna.x,luna.y,luna.height/lunaSprite.originalSize[1]);const entry=config.sprites[config.bar.sprite],width=entry.originalSize[0]-config.bar.insetX*2,height=entry.originalSize[1]-config.bar.insetY*2,left=config.bar.x-width/2,top=config.bar.y-height/2;context.save();context.beginPath();context.roundRect(left,top,width,height,height/2);context.clip();context.fillStyle=config.bar.color;context.fillRect(left,top,width*progress,height);context.restore();sprite(config.bar.sprite,config.bar.x,config.bar.y);for(const [index,letter] of config.letters.entries()){const pose=loadingLetterPose(atTick,index,config.letterDuration);if(!pose.alpha)continue;context.save();context.globalAlpha=pose.alpha;sprite(letter.sprite,letter.x,letter.y+pose.y);context.restore()}context.restore()}
 function animate(now){if(view.hidden)return;if(document.hidden){lastFrame=undefined;animationFrame=requestAnimationFrame(animate);return}if(assets){tick+=lastFrame===undefined?0:Math.max(0,Math.min(1,(now-lastFrame)*60/1000));if(test)update(tick/assets.config.previewTicks)}lastFrame=now;render();animationFrame=requestAnimationFrame(animate)}
 function update(value){progress=Math.max(progress,Math.min(1,Math.max(0,Number(value)||0)));const percent=Math.floor(progress*100);fill.style.width=percent+'%';percentage.textContent=percent+'%';bar.setAttribute('aria-valuenow',String(percent));if(progress===1)view.setAttribute('aria-busy','false')}
 function show(){cancelAnimationFrame(animationFrame);progress=tick=0;lastFrame=undefined;test=false;onExit=undefined;label.textContent='NOW LOADING';label.style.cssText='position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)';exit.hidden=true;testControls.hidden=true;view.hidden=false;view.style.display='block';view.setAttribute('aria-busy','true');update(0);render();animationFrame=requestAnimationFrame(animate)}
 function hide(){cancelAnimationFrame(animationFrame);lastFrame=undefined;test=false;view.hidden=true;view.style.display='none';view.setAttribute('aria-busy','false')}
 function fail(error,back){test=false;testControls.hidden=true;label.textContent='載入失敗，請重新整理';label.title=String(error?.message||error);label.style.cssText='position:absolute;left:640px;top:570px;transform:translateX(-50%);font:18px system-ui;color:white';view.setAttribute('aria-busy','false');onExit=back;exit.hidden=!back}
 function showTest(back){show();test=true;onExit=back;testControls.hidden=false}
 function confirmTest(){if(!test)return false;const back=onExit;hide();back?.();return true}
 exit.addEventListener('click',()=>{const back=onExit;hide();back?.()});reload.addEventListener('click',()=>showTest(onExit));confirm.addEventListener('click',confirmTest);
 return {ready,show,showTest,confirmTest,hide,update,fail,render,snapshot:()=>({loaded:!!assets,progress,tick,test,lunaFrame:assets?Math.floor(tick/assets.config.luna.frameTicks)%assets.config.luna.frames.length:0,letters:assets?assets.config.letters.map((letter,index)=>({...letter,...loadingLetterPose(tick,index,assets.config.letterDuration)})):[]}),get visible(){return !view.hidden},get progress(){return progress}};
}

