import {assetUrl} from './asset-paths.js?v=02362';
import {createTitleStage} from '../Stage/Title/title-stage.js?v=02362-camera2';
import {createLogoIntro} from '../Data/Logo/logo-intro.js?v=loading1';
import {createSelectScreen} from './select-screen.js?v=selection7';
import {createLoadingScreen} from './loading-screen.js?v=loading1';

export function createPalaceMenu(api){
 const defaults={difficulty:4,timer:'99',master:100,bgm:100,sfx:100};let options={...defaults};try{const saved=JSON.parse(localStorage.getItem('palace-options-v1'));for(const key of Object.keys(defaults))if(saved&&saved[key]!==undefined)options[key]=saved[key]}catch{}
 options.difficulty=Math.max(1,Math.min(8,Number(options.difficulty)||4));options.timer=options.timer==='infinite'?'infinite':String(Math.max(15,Math.min(99,Number(options.timer)||99)));for(const key of ['master','bgm','sfx'])options[key]=Math.max(0,Math.min(100,Number(options[key])||0));
 let mode='home',selected=0,logoIntro=null,homeFading=false;const sounds=new Set(),music=new Audio(assetUrl('./title-bgm.mp3'));music.loop=true;
 const overlay=document.createElement('div');overlay.id='palaceMenu';overlay.style.cssText='position:fixed;inset:0;z-index:40;background:#05050d';
 const titleStage=createTitleStage(overlay);titleStage.ready.catch(error=>console.error('Title stage',error));
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';overlay.appendChild(canvas);const context=canvas.getContext('2d');
 const panel=document.createElement('div');panel.style.cssText='position:absolute;left:50%;top:72%;transform:translateX(-50%);text-align:center;min-width:260px';overlay.appendChild(panel);document.body.appendChild(overlay);
 const selection=createSelectScreen(overlay,{confirm:(next,choice)=>start(next,choice),back:()=>{mode='home';showHome()}});selection.ready.catch(error=>console.error('Selection',error));
 const loading=createLoadingScreen(document.body,'battleLoading');let starting=false;
 function playMusic(){if(overlay.hidden)return;volume();music.play().then(()=>{if(overlay.hidden)music.pause()}).catch(()=>{})}
 document.addEventListener('pointerdown',playMusic,true);document.addEventListener('keydown',playMusic,true);
 const logoLink=document.createElement('a');logoLink.id='tsukinoLink';logoLink.href='https://tsukinoaiplus.com';logoLink.target='_blank';logoLink.rel='noopener noreferrer';logoLink.setAttribute('aria-label','TsukinoAi+ 官方網站');logoLink.style.cssText='position:absolute;display:block';overlay.appendChild(logoLink);
 let optionLayers=[];const optionReady=fetch(assetUrl('./system_webp.json?v=02362')).then(response=>response.json()).then(async data=>{optionLayers=await Promise.all(['200,1','1,0'].map(async key=>{const entry=data.sprites[key],image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=assetUrl('./'+entry.file)});return {...entry,image}}));draw()});optionReady.catch(error=>console.error('Options artwork',error));
 const homeButton=document.createElement('button');homeButton.textContent='Menu';homeButton.style.cssText='font-size:11px;padding:3px 6px;border-radius:4px';document.querySelector('#inputPanel').appendChild(homeButton);
 let layers=[],animation,atlases=[],started=performance.now();const ready=fetch(assetUrl('./title_layers.json?v=02362')).then(response=>response.json()).then(async data=>{layers=await Promise.all(data.layers.filter(layer=>[0,1].includes(layer.sprite[0])).map(async layer=>{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=assetUrl('./'+layer.file+'?v=02362')});return {...layer,image}}));draw()});
 function draw(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const fit=Math.min(innerWidth/1280,innerHeight/720),left=(innerWidth-1280*fit)/2,top=(innerHeight-720*fit)/2;context.clearRect(0,0,innerWidth,innerHeight);context.translate(left,top);context.scale(fit,fit);context.beginPath();context.rect(0,0,1280,720);context.clip();logoLink.style.display=mode==='home'?'block':'none';Object.assign(logoLink.style,{left:(left+970*fit)+'px',top:(top+590*fit)+'px',width:(300*fit)+'px',height:(105*fit)+'px'});if(mode==='select')return;if(mode==='options'){for(const layer of optionLayers)context.drawImage(layer.image,640-layer.axisX,-layer.axisY);return}const tick=Math.floor((performance.now()-started)*60/1000);for(const layer of layers){const action=layer.sprite[0];if(layer.sprite[0]===10&&layer.sprite[1]===1)continue;if(animation&&[21,30].includes(action)){const entry=animation.animated[String(action)];context.drawImage(atlases[action===21?0:1],entry.x,entry.y)}else if(action===0){context.drawImage(layer.image,640-layer.axisX,-layer.axisY+Math.min(0,-75+Math.min(tick,15)*5))}else context.drawImage(layer.image,640-layer.axisX,-layer.axisY);if(layer===layers[0]&&layers[7]){const star=layers[7];context.save();context.globalCompositeOperation='lighter';context.globalAlpha=50/256;for(const [x,y] of [[330,-120],[1220,90]]){const startX=((640+x-star.axisX-24*tick)%star.image.width+star.image.width)%star.image.width,startY=((y-star.axisY+10*tick)%star.image.height+star.image.height)%star.image.height;for(let px=startX-star.image.width;px<1280;px+=star.image.width)for(let py=startY-star.image.height;py<720;py+=star.image.height)context.drawImage(star.image,px,py)}context.restore()}}}
 function volume(){music.volume=options.master*options.bgm/10000;for(const sound of sounds)sound.volume=options.master*options.sfx/10000}
 function sound(audio){sounds.add(audio);audio.volume=options.master*options.sfx/10000;audio.addEventListener('ended',()=>sounds.delete(audio),{once:true});audio.addEventListener('error',()=>sounds.delete(audio),{once:true});return audio}
 function button(label,action){const element=document.createElement('button');element.textContent=label;element.style.cssText='display:block;margin:auto;border:0;background:transparent;color:#ffd66b;text-shadow:0 0 8px #fff;font:32px Georgia;padding:2px 14px';element.addEventListener('click',action);panel.appendChild(element);return element}
 function save(){try{localStorage.setItem('palace-options-v1',JSON.stringify(options))}catch{}volume()}
 function showHome(internal=false){if(logoIntro&&!logoIntro.finished&&internal!==true)return;selection.hide();loading.hide();if(['vs','training','watch'].includes(mode))music.currentTime=0;mode='home';draw();overlay.hidden=false;panel.style.top='72%';panel.replaceChildren();for(const [index,label] of ['VS','Training','Watch','Options'].entries()){const element=button(label,()=>index===3?showOptions():showSelect(label.toLowerCase()));element.style.opacity=index===selected?'1':'.65'}api.pause(true);volume();playMusic()}
 function showSelect(next){if(logoIntro&&!logoIntro.finished)return;mode='select';panel.replaceChildren();draw();selection.show(next);api.pause(true)}
 async function start(next,choice){if(starting||logoIntro&&!logoIntro.finished)return;if(choice&&(choice.players.some(id=>id!=='SailorVenus')||choice.stage!=='training'))throw Error('Unsupported selection');starting=true;mode='loading';selection.hide();panel.replaceChildren();loading.show();api.pause(true);try{await api.ready(progress=>loading.update(progress));mode=next;overlay.hidden=true;music.pause();api.start(next,next==='training'?'infinite':options.timer,choice);api.pause(false);loading.update(1);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));loading.hide()}catch(error){console.error('Battle loading',error);loading.fail(error,showHome)}finally{starting=false}}
 function showOptions(){mode='options';draw();volume();playMusic();panel.style.top='28%';panel.replaceChildren();const box=document.createElement('div');box.style.cssText='padding:18px;background:#080b27dd;border:1px solid #bda451;border-radius:8px;color:white';panel.appendChild(box);
  for(const [key,label,min,max] of [['difficulty','Difficulty',1,8],['master','Master Volume',0,100],['bgm','BGM Volume',0,100],['sfx','SFX Volume',0,100]]){const row=document.createElement('label');row.style.cssText='display:block;padding:8px;text-align:left';const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.value=options[key];const value=document.createElement('span');value.textContent=options[key]+(key==='difficulty'?'':'%');row.append(label+' ',input,value);input.addEventListener('input',()=>{options[key]=Number(input.value);value.textContent=input.value+(key==='difficulty'?'':'%');save()});box.appendChild(row)}
  const timer=document.createElement('select');timer.id='optionTimer';for(const value of ['infinite',...Array.from({length:85},(_,index)=>String(index+15))]){const item=document.createElement('option');item.value=value;item.textContent=value==='infinite'?'None':value;timer.appendChild(item)}timer.value=options.timer;timer.addEventListener('change',()=>{options.timer=timer.value;save()});box.append('Timer ',timer);button('Key Config',()=>api.keyConfig());button('Back',showHome);
 }
 homeButton.addEventListener('click',showHome);window.addEventListener('resize',draw);
 document.addEventListener('keydown',event=>{if(mode==='loading'){event.preventDefault();event.stopImmediatePropagation();return}if(homeFading)return;if(mode==='select'&&selection.handleKey(event)){event.preventDefault();event.stopImmediatePropagation();return}if(overlay.hidden||document.querySelector('dialog[open]'))return;if(event.code==='Escape'){event.preventDefault();event.stopImmediatePropagation();if(mode==='options')showHome();return}if(event.target.matches('input,select'))return;event.preventDefault();event.stopImmediatePropagation();if(mode==='home'){if(event.code==='ArrowDown'||event.code==='ArrowUp'){selected=(selected+(event.code==='ArrowDown'?1:3))%4;showHome()}else if(event.code==='Enter'){selected===3?showOptions():showSelect(['vs','training','watch'][selected])}}else if(event.code==='Escape')showHome()},true);
 const requested=new URLSearchParams(location.search).get('mode');
 mode='logo';overlay.hidden=true;api.pause(true);logoIntro=createLogoIntro(async()=>{homeFading=true;await Promise.all([ready,titleStage.ready]);showHome(true)});logoIntro.done.then(()=>{homeFading=false;if(['vs','training','watch'].includes(requested))start(requested)});document.addEventListener('keydown',event=>{if(!logoIntro.finished){event.preventDefault();event.stopImmediatePropagation()}},true);
 let lastTitleFrame=performance.now();function animate(){const now=performance.now(),dt=Math.min((now-lastTitleFrame)/1000,.05);lastTitleFrame=now;titleStage.setVisible(!overlay.hidden&&mode==='home');if(!overlay.hidden){draw();if(mode==='home')titleStage.render(dt)}requestAnimationFrame(animate)}requestAnimationFrame(animate);
 return {ready:Promise.all([ready,titleStage.ready]),titleStage,logoIntro,selection,showSelect,sound,options,start,showHome,isWatch:()=>mode==='watch',isHome:()=>mode==='logo'||!overlay.hidden};
}
