import {assetUrl} from './asset-paths.js?v=02362';
import {createTitleStage} from '../Stage/Title/title-stage.js?v=02369';
import {createLogoIntro} from '../Data/Logo/logo-intro.js?v=loading1';
import {createSelectScreen} from './select-screen.js?v=02370';
import {createResultDeclarationScreen} from './result-declaration-screen.js?v=declaration5';
import {createAcsScreen} from './acs-screen.js?v=02369';
import {createMenuEntrance} from './menu-entrance.js?v=02370';
import {createLoadingScreen} from './loading-screen.js?v=loading1';

import {createTitlePresentation} from './title-presentation.js?v=02370';

export function createPalaceMenu(api){
 const presentation=createTitlePresentation();
 const defaults={difficulty:4,timer:'99',master:100,bgm:100,sfx:100};let options={...defaults};try{const saved=JSON.parse(localStorage.getItem('palace-options-v1'));for(const key of Object.keys(defaults))if(saved&&saved[key]!==undefined)options[key]=saved[key]}catch{}
 options.difficulty=Math.max(1,Math.min(8,Number(options.difficulty)||4));options.timer=options.timer==='infinite'?'infinite':String(Math.max(15,Math.min(99,Number(options.timer)||99)));for(const key of ['master','bgm','sfx'])options[key]=Math.max(0,Math.min(100,Number(options[key])||0));
 let battlePlayers=['SailorVenus','SailorVenus'];let mode='home',selected=0,logoIntro=null,homeFading=false;const sounds=new Set(),music=new Audio(assetUrl('./title-bgm.mp3'));music.loop=true;
 const overlay=document.createElement('div');overlay.id='palaceMenu';overlay.style.cssText='position:fixed;inset:0;z-index:40;background:#05050d;overflow:hidden';
 const titleStage=createTitleStage(overlay);titleStage.ready.catch(error=>console.error('Title stage',error));
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';overlay.appendChild(canvas);const context=canvas.getContext('2d');
 const panel=document.createElement('div');panel.style.cssText='position:absolute;left:50%;top:72%;transform:translateX(-50%);text-align:center;min-width:260px';overlay.appendChild(panel);document.body.appendChild(overlay);
 const popup=document.createElement('section');popup.id='settingsPopup';popup.setAttribute('role','dialog');popup.setAttribute('aria-label','Settings');popup.hidden=true;popup.style.cssText='position:absolute;text-align:center;color:white;z-index:2';overlay.appendChild(popup);
 const selection=createSelectScreen(overlay,{preloadACS:()=>Promise.all([acs.ready,resultDeclarations.ready]),confirm:async(next,choice)=>{if(next==='training')start(next,choice);else{await acs.show(next,choice);selection.hide();mode='acs'}},back:()=>{mode='home';showHome()}});selection.ready.catch(error=>console.error('Selection',error));
 const acs=createAcsScreen(overlay,{confirm:start,back:showSelect,sound,declaration:()=>{mode='declaration';music.pause()}});acs.ready.catch(error=>console.error('ACS',error));
 const resultDeclarations=createResultDeclarationScreen(overlay,{sound,complete:showHome});resultDeclarations.ready.catch(error=>console.error('Result declarations',error));
 async function showResult(winner){mode='result';music.pause();api.pause(true);selection.hide();acs.hide();panel.replaceChildren();overlay.hidden=false;await resultDeclarations.ready;resultDeclarations.show(battlePlayers,winner)}
 const loading=createLoadingScreen(document.body,'battleLoading');let starting=false;
 const entrance=createMenuEntrance(overlay,{loading,ready:()=>Promise.all([selection.ready,titleStage.ready]),progress:()=>selection.progress(),onFrame:amount=>{panel.style.opacity=String(1-Math.min(1,amount*3));canvas.style.transform='scale('+(1+amount*14)+')';canvas.style.transformOrigin='50% 50%';canvas.style.opacity=String(Math.max(0,Math.min(1,(.45-amount)/.25)));titleStage.setTravel(amount)},show:next=>next?openSelection(next):showHome()});
 function showSelect(next){if(entrance.active||logoIntro&&!logoIntro.finished)return;if(mode==='home'){mode='entrance';api.pause(true);entrance.run(next)}else openSelection(next)}
 function playMusic(){if(overlay.hidden||mode==='declaration'||mode==='result'||mode==='loading')return;volume();music.play().then(()=>{if(overlay.hidden)music.pause()}).catch(()=>{})}
 document.addEventListener('pointerdown',playMusic,true);document.addEventListener('keydown',playMusic,true);
 const logoLink=document.createElement('a');logoLink.id='tsukinoLink';logoLink.href='https://tsukinoaiplus.com';logoLink.target='_blank';logoLink.rel='noopener noreferrer';logoLink.setAttribute('aria-label','TsukinoAi+ 官方網站');logoLink.style.cssText='position:absolute;display:block';overlay.appendChild(logoLink);
 let optionLayers=[];const optionReady=fetch(assetUrl('./system_webp.json?v=02362')).then(response=>response.json()).then(async data=>{optionLayers=await Promise.all(['200,1','1,0'].map(async key=>{const entry=data.sprites[key],image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=assetUrl('./'+entry.file)});return {...entry,image}}));draw()});optionReady.catch(error=>console.error('Options artwork',error));
 const homeButton=document.createElement('button');homeButton.textContent='Menu';homeButton.style.cssText='font-size:11px;padding:3px 6px;border-radius:4px';document.querySelector('#inputPanel').appendChild(homeButton);
 let layers=[],animation,atlases=[],started=performance.now();const ready=fetch(assetUrl('./title_layers.json?v=02362')).then(response=>response.json()).then(async data=>{layers=await Promise.all(data.layers.filter(layer=>[0,1].includes(layer.sprite[0])).map(async layer=>{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=assetUrl('./'+layer.file+'?v=02362')});return {...layer,image}}));draw()});
 function draw(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const fit=Math.min(innerWidth/1280,innerHeight/720),left=(innerWidth-1280*fit)/2,top=(innerHeight-720*fit)/2;context.clearRect(0,0,innerWidth,innerHeight);context.translate(left,top);context.scale(fit,fit);context.beginPath();context.rect(0,0,1280,720);context.clip();const state=presentation.snapshot();logoLink.style.display=mode==='home'?'block':'none';Object.assign(logoLink.style,{left:(left+970*fit)+'px',top:(top+590*fit)+'px',width:(300*fit)+'px',height:(105*fit)+'px',opacity:String(state.homeFade)});Object.assign(popup.style,{left:(left+320*fit)+'px',top:(top+96*fit)+'px',width:'640px',height:'528px',transform:'scale('+fit+')',transformOrigin:'0 0',opacity:String(state.settings)});if(['home','options','settingsClosing','entrance'].includes(mode))presentation.draw(context,layers,optionLayers);if(mode!=='entrance'){panel.style.opacity=String(state.homeFade*(1-state.settings));panel.style.pointerEvents=mode==='home'?'auto':'none'}}
 function volume(){music.volume=options.master*options.bgm/10000;for(const sound of sounds)sound.volume=options.master*options.sfx/10000}
 function sound(audio){sounds.add(audio);audio.volume=options.master*options.sfx/10000;audio.addEventListener('ended',()=>sounds.delete(audio),{once:true});audio.addEventListener('error',()=>sounds.delete(audio),{once:true});return audio}
 function button(label,action){const element=document.createElement('button');element.textContent=label;element.style.cssText='display:block;margin:auto;border:0;background:transparent;color:#ffd66b;text-shadow:0 0 8px #fff;font:32px Georgia;padding:2px 14px';element.addEventListener('click',action);panel.appendChild(element);return element}
 function save(){try{localStorage.setItem('palace-options-v1',JSON.stringify(options))}catch{}volume()}
 function showHome(internal=false){if(logoIntro&&!logoIntro.finished&&internal!==true)return;entrance.cancel();selection.hide();acs.hide();resultDeclarations.hide();loading.hide();if(['vs','training','watch','declaration','result'].includes(mode))music.currentTime=0;mode='home';popup.hidden=true;presentation.settings(0);if(internal===true)presentation.enter();draw();overlay.hidden=false;panel.style.top='72%';panel.replaceChildren();for(const [index,label] of ['Arcade','VS','Training','Watch','Settings'].entries()){const element=button(label,()=>index===4?showOptions():showSelect(label.toLowerCase()));element.style.opacity=index===selected?'1':'.65'}api.pause(true);volume();playMusic()}
 function openSelection(next){if(logoIntro&&!logoIntro.finished)return;acs.hide();mode='select';panel.replaceChildren();draw();selection.show(next);api.pause(true)}
 async function start(next,choice){if(starting||logoIntro&&!logoIntro.finished)return;if(choice&&(choice.players.some(id=>id!=='SailorVenus')||!['training','moon'].includes(choice.stage)))throw Error('Unsupported selection');battlePlayers=choice?.players?[...choice.players]:['SailorVenus','SailorVenus'];starting=true;mode='loading';selection.hide();acs.hide();panel.replaceChildren();loading.show();api.pause(true);try{await api.ready(progress=>loading.update(progress));await api.prepareStage?.(choice?.stage);mode=next;overlay.hidden=true;music.pause();api.start(next,next==='training'?'infinite':options.timer,choice);api.pause(false);loading.update(1);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));loading.hide()}catch(error){console.error('Battle loading',error);loading.fail(error,showHome)}finally{starting=false}}
 function showOptions(){mode='options';presentation.settings(1);popup.hidden=false;popup.replaceChildren();draw();volume();playMusic();const box=document.createElement('div');box.style.cssText='padding:18px;background:transparent;border:0;color:white;text-shadow:0 1px 3px #080b27';popup.appendChild(box);
  for(const [key,label,min,max] of [['difficulty','Difficulty',1,8],['master','Master Volume',0,100],['bgm','BGM Volume',0,100],['sfx','SFX Volume',0,100]]){const row=document.createElement('label');row.style.cssText='display:block;padding:8px;text-align:left';const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.value=options[key];const value=document.createElement('span');value.textContent=options[key]+(key==='difficulty'?'':'%');row.append(label+' ',input,value);input.addEventListener('input',()=>{options[key]=Number(input.value);value.textContent=input.value+(key==='difficulty'?'':'%');save()});box.appendChild(row)}
  const timer=document.createElement('select');timer.id='optionTimer';for(const value of ['infinite',...Array.from({length:85},(_,index)=>String(index+15))]){const item=document.createElement('option');item.value=value;item.textContent=value==='infinite'?'None':value;timer.appendChild(item)}timer.value=options.timer;timer.addEventListener('change',()=>{options.timer=timer.value;save()});box.append('Timer ',timer);for(const [label,action] of [['Key Config',()=>api.keyConfig()],['Back',closeSettings]]){const element=document.createElement('button');element.textContent=label;element.style.cssText='display:block;margin:18px auto;padding:8px 24px';element.onclick=action;box.appendChild(element)}
 }
 function closeSettings(){mode='settingsClosing';presentation.settings(0)}
 homeButton.addEventListener('click',showHome);window.addEventListener('resize',draw);
 document.addEventListener('keydown',event=>{if(mode==='loading'){event.preventDefault();event.stopImmediatePropagation();return}if(homeFading)return;if(mode==='acs'&&acs.handleKey(event)){event.preventDefault();event.stopImmediatePropagation();return}if(mode==='select'&&selection.handleKey(event)){event.preventDefault();event.stopImmediatePropagation();return}if(overlay.hidden||document.querySelector('dialog[open]'))return;if(event.code==='Escape'){event.preventDefault();event.stopImmediatePropagation();if(mode==='options')closeSettings();return}if(event.target.matches('input,select'))return;event.preventDefault();event.stopImmediatePropagation();if(mode==='home'){if(event.code==='ArrowDown'||event.code==='ArrowUp'){selected=(selected+(event.code==='ArrowDown'?1:4))%5;showHome()}else if(event.code==='Enter'){selected===4?showOptions():showSelect(['arcade','vs','training','watch'][selected])}}else if(event.code==='Escape')showHome()},true);
 const requested=new URLSearchParams(location.search).get('mode');
 mode='logo';overlay.hidden=true;api.pause(true);logoIntro=createLogoIntro(async()=>{homeFading=true;await Promise.all([ready,titleStage.ready,optionReady]);showHome(true)});logoIntro.done.then(()=>{homeFading=false;if(['vs','training','watch'].includes(requested))start(requested)});document.addEventListener('keydown',event=>{if(!logoIntro.finished){event.preventDefault();event.stopImmediatePropagation()}},true);
 let lastTitleFrame=performance.now();function animate(){const now=performance.now(),dt=Math.min((now-lastTitleFrame)/1000,.05);lastTitleFrame=now;presentation.step(dt);if(mode==='settingsClosing'&&presentation.snapshot().settings===0){mode='home';popup.hidden=true}titleStage.setVisible(!overlay.hidden&&(['home','options','settingsClosing','entrance'].includes(mode)));if(!overlay.hidden){draw();if(['home','options','settingsClosing','entrance'].includes(mode))titleStage.render(dt)}requestAnimationFrame(animate)}requestAnimationFrame(animate);
 return {ready:Promise.all([ready,titleStage.ready]),titleStage,logoIntro,selection,acs,resultDeclarations,showResult,showSelect,showSettings:showOptions,closeSettings,presentation,sound,options,start,showHome,isWatch:()=>mode==='watch',isHome:()=>mode==='logo'||!overlay.hidden};
}

