export function reportRank(score){return score>=160000?'SS':score>=130000?'S':score>=110000?'A':score>=90000?'B':score>=70000?'C':'D'}
export function reportRecords(result,best={}){const refreshed={time:best.time===undefined||result.time<best.time,hits:result.hits>(best.hits??-1),score:result.score>(best.score??-1)};return {refreshed,best:{time:refreshed.time?result.time:best.time,hits:Math.max(result.hits,best.hits??0),score:Math.max(result.score,best.score??0)}}}
export function createReportCard(){
 const images={};let age=0,statistics,identifier,records;
 const ready=Promise.all(['RC BG','RCard Title','RCard Continue'].map(async name=>{const image=new Image();image.src='./Data/ReportCard/'+encodeURIComponent(name)+'.webp?v=02377';await image.decode();images[name]=image}));
 function begin(character,winner,snapshot){identifier=character;age=0;statistics={time:snapshot?.koTime||0,hits:snapshot?.hits?.[winner-1]||0,score:snapshot?.totals?.[winner-1]||0};let saved={};try{saved=JSON.parse(localStorage.getItem('palace-report-v1'))||{}}catch{}records=reportRecords(statistics,saved[identifier]);saved[identifier]=records.best;try{localStorage.setItem('palace-report-v1',JSON.stringify(saved))}catch{}}
 function text(context,value,x,y,size,color,align='left',gold=false){context.save();context.translate(x,y);context.scale(1.25,1);context.textAlign=align;context.textBaseline=gold?'alphabetic':'top';context.font='small-caps '+size+'px BlackQuality';context.fillStyle=color;if(gold){const metrics=context.measureText(value);context.translate(0,-metrics.actualBoundingBoxDescent);const gradient=context.createLinearGradient(0,metrics.actualBoundingBoxDescent,0,-metrics.actualBoundingBoxAscent);for(const [stop,shade] of [[0,'#DAAC00'],[.2,'#F6E184'],[.5,'#DB9900'],[.8,'#DDB52B'],[1,'#F9EDAB']])gradient.addColorStop(stop,shade);context.fillStyle=gradient;context.strokeStyle='#CF5A02';context.lineWidth=1.2;context.shadowColor='#CF5A02';context.shadowBlur=.6;context.strokeText(value,0,0)}context.fillText(value,0,0);context.restore()}
 function artwork(context,name,x,y){const image=images[name],width=image.naturalWidth*.5,height=image.naturalHeight*.5;context.drawImage(image,x-width/2,y-height/2,width,height)}
 function background(context,alpha=1){context.save();context.globalAlpha*=alpha;const offset=-(age*.15)%480;for(let vertical=offset;vertical<720;vertical+=480)for(let horizontal=offset;horizontal<1280;horizontal+=480)context.drawImage(images['RC BG'],horizontal,vertical,481,481);context.restore()}
 function draw(context,alpha=1){if(!records)return;context.save();context.globalAlpha*=alpha;artwork(context,'RCard Title',916,130);context.fillStyle='rgba(96,73,122,.2)';context.beginPath();context.roundRect(606,205,620,410,40);context.fill();artwork(context,'RCard Continue',916,666);text(context,'Result',1009,228,48,'#785C99','right');text(context,'Best',1170,228,48,'#785C99','right');for(const [index,key,label] of [[0,'time','KO Time'],[1,'hits','Hit No.'],[2,'score','Score']]){const top=318+index*60,format=value=>key==='time'?Number(value).toFixed(1):String(Math.round(value));text(context,label,664,top,48,'#785C99');text(context,format(statistics[key]),1009,top+4,40,records.refreshed[key]?'#E60068':'#785C99','right');text(context,format(records.best[key]),1170,top+4,40,records.refreshed[key]?'#E60068':'#785C99','right')}const name=identifier.replace(/([a-z])([A-Z])/g,'$1 $2');text(context,name,664,562,48,'#DAAC00','left',true);text(context,reportRank(statistics.score),1170,562,84,'#DAAC00','right',true);context.restore()}
 return {ready,begin,background,draw,step:amount=>age+=amount,snapshot:()=>({statistics,records,rank:statistics?reportRank(statistics.score):null})};
}

