import {assetUrl} from './asset-paths.js?v=02362';
import {createLoadingScreen} from './loading-screen.js?v=02375';
import {createQuotePortrait,preloadQuoteAssets} from './quote-animation.js?v=02376';
export function createSelectScreen(parent,api){
 const view=document.createElement('section');view.id='palaceSelection';view.hidden=true;view.style.cssText='position:absolute;inset:0;background:#05050d;z-index:2';parent.appendChild(view);
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:1;pointer-events:none';view.appendChild(canvas);const context=canvas.getContext('2d');
 const controls=document.createElement('div');controls.style.cssText='position:absolute;width:1280px;height:720px;transform-origin:top left;z-index:2';view.appendChild(controls);
 const loading=createLoadingScreen(view,'selectionLoading');let loaded=false,loadError,completed=0,total=1;
 function countEntries(value){return value.file?1:Object.values(value).reduce((sum,entry)=>sum+countEntries(entry),0)}
 const portraits=[createQuotePortrait(),createQuotePortrait()],portraitTicks=[0,0];
 const hardwareValues=['3do','snes','saturn'],commandValues=['normal','auto'];
 let data,assets,stage3D,phase='p1',targetMode='vs',choices=['SailorVenus','SailorVenus'],stage='random',cursor=16,hardware=['snes','snes'],command=['normal','normal'],confirmed=new Set(),ticks=0,lastTime;
 const stageReady=(api.createStage?Promise.resolve({createSelectStage:api.createStage}):import('../Stage/Select/select-stage.js?v=02376')).then(async module=>{const candidate=module.createSelectStage(view);if(!candidate)return;await candidate.ready;stage3D=candidate}).catch(error=>console.error('Selection 3D stage',error));
 async function loadEntries(value){if(value.file){const image=new Image();image.src=assetUrl('./'+value.file+'?v=selection8');await image.decode();loading.update(++completed/total);return {...value,image}}const result=Array.isArray(value)?[]:{};for(const key of Object.keys(value))result[key]=await loadEntries(value[key]);return result}
 const ready=Promise.all(['Data/Select/select-screen.json','Data/Select/selection-assets.json'].map(path=>fetch(assetUrl('./'+path+'?v=selection8')).then(response=>{if(!response.ok)throw Error('Selection data '+path);return response.json()}))).then(async ([config,manifest])=>{total=countEntries(config.background)+countEntries(manifest)+1;data={...config,background:await loadEntries(config.background)};assets=await loadEntries(manifest);await stageReady;await preloadQuoteAssets();await Promise.all(portraits.map(portrait=>portrait.ready));await api.preloadACS?.();loading.update(1);loaded=true;loading.hide();render()}).catch(error=>{loadError=error;if(!view.hidden)loading.fail(error,()=>{hide();api.back()});throw error});
 function player(){return phase.startsWith('p2')?1:0}
 function selectPlayer(target){phase='p'+(target+1);cursor=data.cells.findIndex(cell=>cell.id===choices[target]&&cell.available);render()}
 function discPosition(entry){if(!stage3D)return entry;const focal=360/Math.tan(Math.PI/12),scale=Math.sqrt((8*8-1.4*1.4)/(7.2*7.2-1.4*1.4)),previousY=360-.2/8*focal,nextY=360-.15/7.2*focal;return {x:640+(entry.x-640)*scale,y:nextY+(entry.y-previousY)*scale,w:entry.w*scale,h:entry.h*scale}}
 function draw(){if(!assets||view.hidden)return;canvas.width=Math.round(innerWidth*devicePixelRatio);canvas.height=Math.round(innerHeight*devicePixelRatio);const fit=Math.min(innerWidth/1280,innerHeight/720);context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);context.clearRect(0,0,innerWidth,innerHeight);if(!stage3D){context.fillStyle='#05050d';context.fillRect(0,0,innerWidth,innerHeight)}context.translate((innerWidth-1280*fit)/2,(innerHeight-720*fit)/2);context.scale(fit,fit);context.beginPath();context.rect(0,0,1280,720);context.clip();
  for(const key of stage3D?['2200,0']:['2000,0','2001,0','2200,0']){const layer=data.background.find(entry=>entry.key===key);if(layer)context.drawImage(layer.image,640-layer.axisX,-layer.axisY)}
  for(const [identifier,entry] of Object.entries(assets.characters)){if(entry.disc){context.save();context.globalAlpha=data.cells.some(cell=>cell.id===identifier&&cell.available)?1:.4;const position=discPosition(entry.disc);context.drawImage(entry.disc.image,position.x,position.y,position.w,position.h);context.restore()}}
  stage3D?.drawSurfaceGlares(context);
  for(const target of targetMode==='arcade'?[0]:[0,1]){const entry=assets.characters[choices[target]],position=data.settings['p'+(target+1)+'.face.offset'].split(',').map(Number),anchor=position[0];for(const kind of ['portrait','name']){const item=entry[kind];if(kind==='portrait'&&choices[target]==='SailorVenus'&&!stage3D?.setPortraits){portraits[target].draw(context,anchor-640+item.x,item.y+position[1],item.w,item.h,Math.min(1,portraitTicks[target]/30));continue}if(item&&(kind!=='portrait'||!stage3D?.setPortraits))context.drawImage(item.image,kind==='name'?anchor-item.w/2:anchor-640+item.x,kind==='portrait'?item.y+position[1]:580+(52.5-item.h)/2,item.w,item.h)}}
  const title=stageTitle();if(phase==='stage'&&title){const item=title[String(Math.floor(ticks/4)%2)]||title['0'];context.drawImage(item.image,item.x,610+(47-item.h)/2,item.w,item.h)}
 }
 function button(label,handler,style=''){const element=document.createElement('button');element.type='button';element.textContent=label;element.style.cssText='position:absolute;border:1px solid #e4ca81;background:#0a163be8;color:#fff;border-radius:8px;font:18px system-ui;padding:6px;'+style;element.addEventListener('click',handler);controls.appendChild(element);return element}
 function artworkButton(key,label,handler,left,top,scale=.75){const entry=assets.buttons[key],width=entry.w*scale,height=entry.h*scale;const element=button('',handler,'left:'+(left-width/2)+'px;top:'+top+'px;width:'+width+'px;height:'+height+'px;background:transparent;border:0;padding:0;touch-action:manipulation;transition:transform 80ms');element.setAttribute('aria-label',label);const image=document.createElement('img');image.src=entry.image.src;image.alt=label;image.draggable=false;image.style.cssText='width:100%;height:100%;pointer-events:none';element.appendChild(image);element.addEventListener('pointerdown',event=>{if(element.disabled)return;element.style.transform='scale(.9)';element.setPointerCapture(event.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture','blur'])element.addEventListener(event,()=>{element.style.transform='scale(1)'});return element}
 function resize(){const fit=Math.min(innerWidth/1280,innerHeight/720);Object.assign(controls.style,{left:(innerWidth-1280*fit)/2+'px',top:(innerHeight-720*fit)/2+'px',transform:'scale('+fit+')'});draw()}
 function completeSelection(){return targetMode==='arcade'?confirmed.has(0):confirmed.size===2}
 function next(){if(!completeSelection())return;if(targetMode==='arcade'){const available=data.cells.filter(cell=>cell.available),opponent=available[Math.floor(Math.random()*available.length)].id;api.confirm(targetMode,{players:[choices[0],opponent],stage:({SailorMoon:'moon',SailorVenus:'moon',SailorJupiter:'moon',SailorChibiMoon:'moon',SailorMercury:'mercury',SailorMars:'mars',SailorPluto:'pluto',SailorNeptune:'pluto',SailorUranus:'pluto',SailorSaturn:'pluto',LadySwatheshia:'swatheshia'})[opponent],hardware:[...hardware],command:[...command]});return}phase='stage';ticks=0;render()}
 function touchConfirm(target){if(confirmed.has(target))confirmed.delete(target);else confirmed.add(target);if(completeSelection()){next();return}render()}
 function confirm(){if(!assets)return;if(phase==='stage'){const available=data.cells.filter(cell=>cell.available);const players=[...choices];if(targetMode==='arcade')players[1]=available[Math.floor(Math.random()*available.length)].id;api.confirm(targetMode,{players,stage:stage==='random'?randomStage():stage,hardware:[...hardware],command:targetMode==='watch'?['auto','auto']:[...command]});return}const target=player();if(phase.endsWith('hardware')&&targetMode!=='watch')phase='p'+(target+1)+'command';else if(phase.endsWith('command')||phase.endsWith('hardware')){confirmed.add(target);if(completeSelection()){next();return}selectPlayer(1-target);return}else phase='p'+(target+1)+'hardware';ticks=0;render()}
 function back(){if(phase==='stage'){const target=targetMode==='arcade'?0:1;confirmed.delete(target);phase='p'+(target+1)+(targetMode==='watch'?'hardware':'command')}else if(phase.endsWith('command'))phase='p'+(player()+1)+'hardware';else if(phase.endsWith('hardware'))phase='p'+(player()+1);else if(player()===1){confirmed.delete(0);phase=targetMode==='watch'?'p1hardware':'p1command'}else{hide();api.back();return}ticks=0;render()}
 function choose(value,target=player(),kind){if(confirmed.has(target)&&phase!=='stage')return;if(kind==='hardware'||(!kind&&phase.endsWith('hardware')))hardware[target]=value;else if(kind==='command'||(!kind&&phase.endsWith('command')))command[target]=value;else if(phase==='stage')stage=value;else{if(!data.cells[value]?.available)return;cursor=value;choices[target]=data.cells[value].id;portraits[target].set('9000');portraitTicks[target]=0}ticks=0;render()}
 function cycle(target,kind){const values=kind==='hardware'?hardwareValues:commandValues,current=kind==='hardware'?hardware[target]:command[target];choose(values[(values.indexOf(current)+1)%values.length],target,kind)}
 function stageTitle(){return assets.stages[({random:'Random',training:'Training',moon:'MPalace',mercury:'Library',mars:'Shrine',pluto:'SDoor',swatheshia:'SThrone'}[stage])]}
 function cycleStage(direction){const values=['random',...data.stages.filter(entry=>entry.available).map(entry=>entry.id)];choose(values[(values.indexOf(stage)+direction+values.length)%values.length])}
 function randomStage(){const values=data.stages.filter(entry=>entry.available).map(entry=>entry.id);return values[Math.floor(Math.random()*values.length)]}
 function modeButtons(target,anchor,locked=false){const items=targetMode==='watch'?[['hardware',hardware[target],0]]:[['hardware',hardware[target],0],['command',command[target],1]];for(const [kind,key,column] of items){const element=artworkButton(key,'P'+(target+1)+' '+kind,()=>cycle(target,kind),targetMode==='watch'?anchor:anchor-100+column*200,555-assets.buttons[key].h*.675/2,.675);element.id=kind+'Selection'+target;element.disabled=locked||confirmed.has(target);element.style.filter=element.disabled?'grayscale(.5)':phase==='p'+(target+1)+kind?'drop-shadow(0 0 8px white)':'none'}}
 function render(){if(view.hidden)return;controls.replaceChildren();if(!loaded)return;renderPortraits();
  if(phase!=='stage'){
   for(const target of targetMode==='arcade'?[0]:[0,1]){const anchor=Number(data.settings['p'+(target+1)+'.face.offset'].split(',')[0]);button('',()=>selectPlayer(target),'left:'+(anchor-170)+'px;top:100px;width:340px;height:390px;background:transparent;border:0').setAttribute('aria-label',target?'Select right character':'Select left character');modeButtons(target,anchor);const element=artworkButton(targetMode==='arcade'?'next':'confirm','P'+(target+1)+' '+(targetMode==='arcade'?'Next':'Confirm'),()=>touchConfirm(target),anchor,655);element.id='confirmSelection'+target;element.style.filter=confirmed.has(target)?'grayscale(.5)':'none';element.setAttribute('aria-pressed',String(confirmed.has(target)))}
   for(const [index,cell] of data.cells.entries()){const sourceDisc=assets.characters[cell.id]?.disc;if(!sourceDisc)continue;const disc=discPosition(sourceDisc);const element=button('',()=>choose(index,player(),'character'),'left:'+disc.x+'px;top:'+disc.y+'px;width:'+disc.w+'px;height:'+disc.h+'px;background:transparent;padding:0');element.dataset.character=cell.id;element.disabled=!cell.available||confirmed.has(player());element.title=cell.id+(cell.available?'':' · 未開放');element.style.border='none'}

  }else{const title=stageTitle(),item=title?.['0'];if(item){const element=button('',()=>cycleStage(1),'left:'+item.x+'px;top:'+(610+(47-item.h)/2)+'px;width:'+item.w+'px;height:'+item.h+'px;background:transparent;border:0;padding:0');element.id='stageTitleSelection';element.setAttribute('aria-label','Change stage')}artworkButton('next','Next',confirm,640,665).id='startSelection';for(const target of targetMode==='arcade'?[0]:[0,1])modeButtons(target,Number(data.settings['p'+(target+1)+'.face.offset'].split(',')[0]),true)}
  button('EXIT',()=>{hide();api.back()},'left:20px;top:20px;width:100px').id='exitSelection';resize();
 }
 function show(mode){targetMode=mode;phase='p1';confirmed.clear();hardware=['snes','snes'];command=['normal','normal'];choices=['SailorVenus','SailorVenus'];portraits.forEach((portrait,index)=>{portrait.set('9000');portraitTicks[index]=0});stage='random';cursor=data?.cells.findIndex(entry=>entry.available)??16;ticks=0;lastTime=undefined;view.hidden=false;if(!loaded){loading.show();loading.update(completed/total);if(loadError)loading.fail(loadError,()=>{hide();api.back()})}stage3D?.setVisible(true);render()}
 function hide(){view.hidden=true;loading.hide();lastTime=undefined;stage3D?.setVisible(false)}
 function handleKey(event){if(view.hidden)return false;if(!loaded)return true;if(['Escape','KeyX','KeyS','Numpad2','NumpadDecimal'].includes(event.code)){if(!event.repeat)back();return true}if(['Enter','KeyZ','KeyA','Numpad1','Numpad0'].includes(event.code)){if(!event.repeat)confirm();return true}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Numpad4','Numpad6','Numpad8','Numpad5'].includes(event.code)){if(assets){if(phase==='stage'){if(['ArrowLeft','ArrowRight','Numpad4','Numpad6'].includes(event.code))cycleStage(['ArrowLeft','Numpad4'].includes(event.code)?-1:1);return true}const modePhase=phase.endsWith('hardware')||phase.endsWith('command');if(modePhase&&!['ArrowUp','ArrowDown','Numpad8','Numpad5'].includes(event.code))return true;const direction=['ArrowLeft','ArrowUp','Numpad4','Numpad8'].includes(event.code)?-1:1,values=phase==='stage'?data.stages.filter(entry=>entry.available).map(entry=>entry.id):phase.endsWith('hardware')?hardwareValues:phase.endsWith('command')?commandValues:data.cells.map((entry,index)=>entry.available?index:-1).filter(index=>index>=0),current=phase==='stage'?stage:phase.endsWith('hardware')?hardware[player()]:phase.endsWith('command')?command[player()]:cursor;choose(values[(values.indexOf(current)+direction+values.length)%values.length])}return true}return false}
 function renderPortraits(){if(!stage3D?.setPortraits||!assets)return;stage3D.setPortraits(choices.map((identifier,target)=>{if(targetMode==='arcade'&&target===1)return null;const item=assets.characters[identifier]?.portrait;if(!item)return null;const position=data.settings['p'+(target+1)+'.face.offset'].split(',').map(Number),animated=identifier==='SailorVenus',image=animated?portraits[target].canvas:item.image,width=image.width/image.height*item.h;return {...item,image,w:width,x:position[0]-640+item.x+(item.w-width)/2,y:position[1]+item.y,opacity:animated?Math.min(1,portraitTicks[target]/30):1}}))}
 function animate(time){if(!view.hidden){const dt=lastTime===undefined?0:Math.min((time-lastTime)/1000,.05);ticks+=dt*60;portraits.forEach((portrait,index)=>{portrait.step(dt*60);portraitTicks[index]+=dt*60});lastTime=time;renderPortraits();stage3D?.setVisible(true);stage3D?.render(dt);draw()}requestAnimationFrame(animate)}requestAnimationFrame(animate);window.addEventListener('resize',resize);
 return {ready,show,hide,handleKey,draw,progress:()=>loaded?1:completed/total,snapshot:()=>({phase,mode:targetMode,players:[...choices],hardware:[...hardware],command:[...command],confirmed:[...confirmed],stage,visible:!view.hidden,effects:stage3D?.snapshot()})};
}

