import {assetUrl} from './asset-paths.js?v=02362';
export function createSelectScreen(parent,api){
 const view=document.createElement('section');view.id='palaceSelection';view.hidden=true;view.style.cssText='position:absolute;inset:0;background:#05050d;z-index:2';parent.appendChild(view);
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:1;pointer-events:none';view.appendChild(canvas);const context=canvas.getContext('2d');
 const controls=document.createElement('div');controls.style.cssText='position:absolute;width:1280px;height:720px;transform-origin:top left;z-index:2';view.appendChild(controls);
 const hardwareValues=['3do','snes','saturn'],commandValues=['normal','auto'];
 let data,assets,stage3D,phase='p1',targetMode='vs',choices=['SailorVenus','SailorVenus'],stage='training',cursor=16,hardware=['3do','3do'],command=['normal','normal'],confirmed=new Set(),ticks=0,lastTime;
 const stageReady=(api.createStage?Promise.resolve({createSelectStage:api.createStage}):import('../Stage/Select/select-stage.js?v=selection5')).then(async module=>{const candidate=module.createSelectStage(view);if(!candidate)return;await candidate.ready;stage3D=candidate}).catch(error=>console.error('Selection 3D stage',error));
 async function loadEntries(value){if(value.file){const image=new Image();image.src=assetUrl('./'+value.file+'?v=selection5');await image.decode();return {...value,image}}const result=Array.isArray(value)?[]:{};for(const key of Object.keys(value))result[key]=await loadEntries(value[key]);return result}
 const ready=Promise.all(['Data/Select/select-screen.json','Data/Select/selection-assets.json'].map(path=>fetch(assetUrl('./'+path+'?v=selection5')).then(response=>{if(!response.ok)throw Error('Selection data '+path);return response.json()}))).then(async ([config,manifest])=>{data={...config,background:await loadEntries(config.background)};assets=await loadEntries(manifest);await stageReady;render()});
 function player(){return phase.startsWith('p2')?1:0}
 function selectPlayer(target){phase='p'+(target+1);cursor=data.cells.findIndex(cell=>cell.id===choices[target]&&cell.available);render()}
 function discPosition(entry){if(!stage3D)return entry;const focal=360/Math.tan(Math.PI/12),scale=Math.sqrt((8*8-1.4*1.4)/(7.2*7.2-1.4*1.4)),previousY=360-.2/8*focal,nextY=360-.15/7.2*focal;return {x:640+(entry.x-640)*scale,y:nextY+(entry.y-previousY)*scale,w:entry.w*scale,h:entry.h*scale}}
 function draw(){if(!assets||view.hidden)return;canvas.width=Math.round(innerWidth*devicePixelRatio);canvas.height=Math.round(innerHeight*devicePixelRatio);const fit=Math.min(innerWidth/1280,innerHeight/720);context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);context.clearRect(0,0,innerWidth,innerHeight);if(!stage3D){context.fillStyle='#05050d';context.fillRect(0,0,innerWidth,innerHeight)}context.translate((innerWidth-1280*fit)/2,(innerHeight-720*fit)/2);context.scale(fit,fit);
  for(const key of stage3D?['2200,0']:['2000,0','2001,0','2200,0']){const layer=data.background.find(entry=>entry.key===key);if(layer)context.drawImage(layer.image,640-layer.axisX,-layer.axisY)}
  for(const [identifier,entry] of Object.entries(assets.characters)){if(entry.disc){context.save();context.globalAlpha=data.cells.some(cell=>cell.id===identifier&&cell.available)?1:.4;const position=discPosition(entry.disc);context.drawImage(entry.disc.image,position.x,position.y,position.w,position.h);context.restore()}}
  stage3D?.drawSurfaceGlares(context);
  for(const target of [0,1]){const entry=assets.characters[choices[target]],position=data.settings['p'+(target+1)+'.face.offset'].split(',').map(Number),anchor=position[0];for(const kind of ['portrait','name']){const item=entry[kind];if(item)context.drawImage(item.image,anchor-640+item.x,item.y+(kind==='portrait'?position[1]:0),item.w,item.h)}}
  const title=assets.stages[({training:'Training',moon:'MPalace',mercury:'Library',mars:'Shrine',pluto:'SDoor',swatheshia:'SThrone'}[stage])];if(phase==='stage'&&title){const item=title[String(Math.floor(ticks/4)%2)]||title['0'];context.drawImage(item.image,item.x,item.y,item.w,item.h)}
 }
 function button(label,handler,style=''){const element=document.createElement('button');element.type='button';element.textContent=label;element.style.cssText='position:absolute;border:1px solid #e4ca81;background:#0a163be8;color:#fff;border-radius:8px;font:18px system-ui;padding:6px;'+style;element.addEventListener('click',handler);controls.appendChild(element);return element}
 function artworkButton(key,label,handler,left,top){const entry=assets.buttons[key],width=entry.w*.75,height=entry.h*.75;const element=button('',handler,'left:'+(left-width/2)+'px;top:'+top+'px;width:'+width+'px;height:'+height+'px;background:transparent;border:0;padding:0;touch-action:manipulation;transition:transform 80ms');element.setAttribute('aria-label',label);const image=document.createElement('img');image.src=entry.image.src;image.alt=label;image.draggable=false;image.style.cssText='width:100%;height:100%;pointer-events:none';element.appendChild(image);element.addEventListener('pointerdown',event=>{if(element.disabled)return;element.style.transform='scale(.9)';element.setPointerCapture(event.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture','blur'])element.addEventListener(event,()=>{element.style.transform='scale(1)'});return element}
 function resize(){const fit=Math.min(innerWidth/1280,innerHeight/720);Object.assign(controls.style,{left:(innerWidth-1280*fit)/2+'px',top:(innerHeight-720*fit)/2+'px',transform:'scale('+fit+')'});draw()}
 function next(){if(targetMode!=='training'&&confirmed.size<2)return;phase='stage';ticks=0;render()}
 function touchConfirm(target){if(confirmed.has(target))confirmed.delete(target);else confirmed.add(target);render()}
 function confirm(){if(!assets)return;if(phase==='stage'){api.confirm(targetMode,{players:[...choices],stage,hardware:[...hardware],command:[...command]});return}const target=player();if(phase.endsWith('hardware'))phase='p'+(target+1)+'command';else if(phase.endsWith('command')){if(targetMode==='training'){next();return}confirmed.add(target);if(confirmed.size===2){next();return}selectPlayer(1-target);return}else phase='p'+(target+1)+'hardware';ticks=0;render()}
 function back(){if(phase==='stage'){confirmed.delete(targetMode==='training'?0:1);phase=targetMode==='training'?'p1command':'p2command'}else if(phase.endsWith('command'))phase='p'+(player()+1)+'hardware';else if(phase.endsWith('hardware'))phase='p'+(player()+1);else if(player()===1){confirmed.delete(0);phase='p1command'}else{hide();api.back();return}ticks=0;render()}
 function choose(value,target=player(),kind){if(confirmed.has(target)&&phase!=='stage')return;if(kind==='hardware'||(!kind&&phase.endsWith('hardware')))hardware[target]=value;else if(kind==='command'||(!kind&&phase.endsWith('command')))command[target]=value;else if(phase==='stage')stage=value;else{if(!data.cells[value]?.available)return;cursor=value;choices[target]=data.cells[value].id}ticks=0;render()}
 function cycle(target,kind){const values=kind==='hardware'?hardwareValues:commandValues,current=kind==='hardware'?hardware[target]:command[target];choose(values[(values.indexOf(current)+1)%values.length],target,kind)}
 function render(){if(view.hidden)return;controls.replaceChildren();if(!assets){button('Loading…',()=>{},'left:520px;top:320px;width:240px');return}
  if(phase!=='stage'){
   for(const target of targetMode==='training'?[0]:[0,1]){const anchor=Number(data.settings['p'+(target+1)+'.face.offset'].split(',')[0]);const selector=button('P'+(target+1),()=>selectPlayer(target),'left:'+(anchor-25)+'px;top:95px;width:50px');selector.dataset.player=String(target);selector.style.opacity=player()===target?'1':'.55';for(const [kind,key,column] of [['hardware',hardware[target],0],['command',command[target],1]]){const element=artworkButton(key,'P'+(target+1)+' '+kind,()=>cycle(target,kind),anchor-110+column*220,525);element.id=kind+'Selection'+target;element.disabled=confirmed.has(target);element.style.filter=confirmed.has(target)?'grayscale(1)':phase==='p'+(target+1)+kind?'drop-shadow(0 0 8px white)':'none'}const element=artworkButton(targetMode==='training'?'next':'confirm','P'+(target+1)+' '+(targetMode==='training'?'Next':'Confirm'),()=>targetMode==='training'?next():touchConfirm(target),anchor,595);element.id='confirmSelection'+target;element.style.filter=confirmed.has(target)?'grayscale(1)':'none';element.setAttribute('aria-pressed',String(confirmed.has(target)))}
   for(const [index,cell] of data.cells.entries()){const sourceDisc=assets.characters[cell.id]?.disc;if(!sourceDisc)continue;const disc=discPosition(sourceDisc);const element=button('',()=>choose(index,player(),'character'),'left:'+disc.x+'px;top:'+disc.y+'px;width:'+disc.w+'px;height:'+disc.h+'px;background:transparent;padding:0');element.dataset.character=cell.id;element.disabled=!cell.available||confirmed.has(player());element.title=cell.id+(cell.available?'':' · 未開放');element.style.border=index===cursor?'2px solid #fff6a3':'none'}
   if(targetMode!=='training'){const element=artworkButton('next','Next',next,640,625);element.id='nextSelection';element.disabled=confirmed.size<2;element.style.opacity=element.disabled?'.45':'1'}
  }else{data.stages.forEach((entry,index)=>{const element=button(entry.name,()=>choose(entry.id),'left:480px;top:'+(180+index*57)+'px;width:320px;height:46px');element.dataset.stage=entry.id;element.disabled=!entry.available});artworkButton('next','Start Fight',confirm,710,610).id='startSelection'}
  button('Back',back,'left:490px;top:665px;width:100px').id='backSelection';resize();
 }
 function show(mode){targetMode=mode;phase='p1';confirmed.clear();hardware=['3do','3do'];command=['normal','normal'];choices=['SailorVenus','SailorVenus'];stage='training';cursor=data?.cells.findIndex(entry=>entry.available)??16;ticks=0;lastTime=undefined;view.hidden=false;stage3D?.setVisible(true);render()}
 function hide(){view.hidden=true;lastTime=undefined;stage3D?.setVisible(false)}
 function handleKey(event){if(view.hidden)return false;if(['Escape','KeyX','KeyS','Numpad2','NumpadDecimal'].includes(event.code)){if(!event.repeat)back();return true}if(['Enter','KeyZ','KeyA','Numpad1','Numpad0'].includes(event.code)){if(!event.repeat)confirm();return true}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Numpad4','Numpad6','Numpad8','Numpad5'].includes(event.code)){if(assets){const modePhase=phase.endsWith('hardware')||phase.endsWith('command');if(modePhase&&!['ArrowUp','ArrowDown','Numpad8','Numpad5'].includes(event.code))return true;const direction=['ArrowLeft','ArrowUp','Numpad4','Numpad8'].includes(event.code)?-1:1,values=phase==='stage'?data.stages.filter(entry=>entry.available).map(entry=>entry.id):phase.endsWith('hardware')?hardwareValues:phase.endsWith('command')?commandValues:data.cells.map((entry,index)=>entry.available?index:-1).filter(index=>index>=0),current=phase==='stage'?stage:phase.endsWith('hardware')?hardware[player()]:phase.endsWith('command')?command[player()]:cursor;choose(values[(values.indexOf(current)+direction+values.length)%values.length])}return true}return false}
 function animate(time){if(!view.hidden){const dt=lastTime===undefined?0:Math.min((time-lastTime)/1000,.05);ticks+=dt*60;lastTime=time;stage3D?.setVisible(true);stage3D?.render(dt);draw()}requestAnimationFrame(animate)}requestAnimationFrame(animate);window.addEventListener('resize',resize);
 return {ready,show,hide,handleKey,draw,snapshot:()=>({phase,mode:targetMode,players:[...choices],hardware:[...hardware],command:[...command],confirmed:[...confirmed],stage,visible:!view.hidden,effects:stage3D?.snapshot()})};
}
