import {assetUrl} from './asset-paths.js?v=02362';
export function createSelectScreen(parent,api){
 const view=document.createElement('section');view.id='palaceSelection';view.hidden=true;view.style.cssText='position:absolute;inset:0;background:#05050d;z-index:2';parent.appendChild(view);
 const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%';view.appendChild(canvas);const context=canvas.getContext('2d');
 const controls=document.createElement('div');controls.style.cssText='position:absolute;width:1280px;height:720px;transform-origin:top left';view.appendChild(controls);
 let data,phase='p1',targetMode='vs',choices=['SailorVenus','SailorVenus'],stage='training',cursor=15;
 const load=async entry=>{const image=new Image();image.src=assetUrl('./'+entry.file);await image.decode();return {...entry,image}};
 const ready=fetch(assetUrl('./Data/Select/select-screen.json?v=02362')).then(response=>{if(!response.ok)throw Error('Selection data');return response.json()}).then(async config=>{data={...config,background:await Promise.all(config.background.map(load)),portraits:await Promise.all(config.portraits.map(load))};render()});
 function draw(){if(!data||view.hidden)return;canvas.width=Math.round(innerWidth*devicePixelRatio);canvas.height=Math.round(innerHeight*devicePixelRatio);const fit=Math.min(innerWidth/1280,innerHeight/720);context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);context.fillStyle='#05050d';context.fillRect(0,0,innerWidth,innerHeight);context.translate((innerWidth-1280*fit)/2,(innerHeight-720*fit)/2);context.scale(fit,fit);
  for(const key of ['2000,0','2001,0','2200,0']){const layer=data.background.find(entry=>entry.key===key);context.drawImage(layer.image,640-layer.axisX,-layer.axisY)}
  const map=data.background.find(entry=>entry.key==='2002,0');context.drawImage(map.image,435,120,410,415,435,120,410,415);
  const portrait=data.portraits[0];for(const player of [1,2]){const position=data.settings['p'+player+'.face.offset'].split(',').map(Number);context.save();context.beginPath();context.rect(player===1?0:860,45,420,650);context.clip();context.globalAlpha=phase==='p1'&&player===2?.45:1;context.drawImage(portrait.image,position[0]-portrait.axisX,position[1]-portrait.axisY);context.restore()}
 }
 function button(label,handler,style=''){const element=document.createElement('button');element.type='button';element.textContent=label;element.style.cssText='position:absolute;border:1px solid #e4ca81;background:#0a163be8;color:#fff;border-radius:8px;font:20px system-ui;padding:8px;'+style;element.addEventListener('click',handler);controls.appendChild(element);return element}
 function resize(){const fit=Math.min(innerWidth/1280,innerHeight/720);Object.assign(controls.style,{left:(innerWidth-1280*fit)/2+'px',top:(innerHeight-720*fit)/2+'px',transform:'scale('+fit+')'});draw()}
 function confirm(){if(!data)return;if(phase==='p1'||phase==='p2'){const cell=data.cells[cursor];if(!cell?.available)return;choices[phase==='p1'?0:1]=cell.id;phase=phase==='p1'?'p2':'stage';render()}else api.confirm(targetMode,{players:[...choices],stage})}
 function back(){if(phase==='stage')phase='p2';else if(phase==='p2')phase='p1';else{hide();api.back();return}render()}
 function render(){if(view.hidden)return;controls.replaceChildren();if(!data){button('Loading…',()=>{},'left:520px;top:320px;width:240px');return}const title=document.createElement('h2');title.textContent=targetMode.toUpperCase()+' · '+(phase==='stage'?'SELECT STAGE':phase.toUpperCase()+' SELECT CHARACTER');title.style.cssText='position:absolute;top:74px;left:350px;width:580px;margin:0;text-align:center;color:#fff;text-shadow:0 2px 8px #142951;font:30px Georgia';controls.appendChild(title);
  if(phase!=='stage'){for(const [index,cell] of data.cells.entries()){if(cell.id==='x')continue;const label=cell.id.replace(/^Sailor/,'').replace(/^Lady/,'');const element=button(label,()=>{cursor=index;render()},'left:'+(434+index%6*69)+'px;top:'+(392+Math.floor(index/6)*48)+'px;width:66px;height:44px;font-size:14px;padding:2px');element.dataset.character=cell.id;element.disabled=!cell.available;element.title=cell.available?'Select '+label:'尚未接入網頁版';element.style.opacity=cell.available?'1':'.4';if(index===cursor){element.style.border='2px solid #fff6a3';element.style.background='#916418ef'}}}
  else{for(const [index,entry] of data.stages.entries()){const element=button(entry.name+(entry.available?'':' · 未開放'),()=>{stage=entry.id;render()},'left:480px;top:'+(215+index*48)+'px;width:320px;height:42px;font-size:18px');element.dataset.stage=entry.id;element.disabled=!entry.available;element.style.opacity=entry.available?'1':'.4';if(entry.id===stage)element.style.border='2px solid #fff6a3'}}
  const help=document.createElement('p');help.textContent='目前可用：Sailor Venus ／ Training';help.style.cssText='position:absolute;left:420px;top:574px;width:440px;color:#fff;text-align:center;font-size:18px;text-shadow:0 1px 4px #000';controls.appendChild(help);
  const confirmButton=button(phase==='stage'?'Start Fight':'Confirm '+phase.toUpperCase(),confirm,'left:565px;top:625px;width:180px');confirmButton.id='confirmSelection';button('Back',back,'left:450px;top:625px;width:100px').id='backSelection';resize();
 }
 function show(mode){targetMode=mode;phase='p1';cursor=data?.cells.findIndex(entry=>entry.available)??15;view.hidden=false;render()}
 function hide(){view.hidden=true}
 function handleKey(event){if(view.hidden)return false;if(event.code==='Escape'){back();return true}if(['Enter','KeyZ','Numpad0'].includes(event.code)){if(!event.repeat)confirm();return true}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Numpad4','Numpad6','Numpad8','Numpad5'].includes(event.code)){if(data&&phase!=='stage'){const available=data.cells.map((entry,index)=>entry.available?index:-1).filter(index=>index>=0);const direction=['ArrowLeft','ArrowUp','Numpad4','Numpad8'].includes(event.code)?-1:1;cursor=available[(available.indexOf(cursor)+direction+available.length)%available.length];render()}return true}return false}
 window.addEventListener('resize',resize);
 return {ready,show,hide,handleKey,draw,snapshot:()=>({phase,mode:targetMode,players:[...choices],stage,visible:!view.hidden})};
}
