const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..'),config=JSON.parse(fs.readFileSync(path.join(root,'Data/Loading/loading-atlas.json'),'utf8'));
const draws=[],context={setTransform(){},fillRect(...args){draws.push({type:'fill',color:this.fillStyle,args})},translate(){},scale(){},save(){},restore(){},beginPath(){},rect(){},roundRect(){},clip(){},drawImage(...args){draws.push({type:'image',args})}};
function element(){return {style:{},children:[],attributes:{},hidden:false,appendChild(child){this.children.push(child)},setAttribute(key,value){this.attributes[key]=value},addEventListener(key,callback){this[key]=callback},getContext(){return context}}}
let fetches=0,bitmaps=0;
const sandbox={document:{body:element(),createElement:element},URL,innerWidth:1280,innerHeight:720,devicePixelRatio:1,requestAnimationFrame:()=>1,cancelAnimationFrame(){},fetch:async()=>{fetches++;return {ok:true,json:async()=>config}},Image:class{async decode(){}},createImageBitmap:async()=>{bitmaps++;return {}},console};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'Engine/letter-animation.js'),'utf8').replace(/^export /gm,''),sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'Engine/loading-screen.js'),'utf8').replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'').replaceAll('import.meta.url',JSON.stringify('http://localhost/Engine/loading-screen.js'))+';globalThis.createLoadingScreen=createLoadingScreen;globalThis.loadingLetterPose=loadingLetterPose',sandbox);
const loading=sandbox.createLoadingScreen(),view=sandbox.document.body.children[0],content=view.children[1],bar=content.children[1];
assert.equal(loading.visible,false);assert.ok(view.style.cssText.includes('background:#fff'));loading.show();assert.equal(loading.progress,0);loading.update(.4);assert.equal(bar.attributes['aria-valuenow'],'40');loading.update(.2);assert.equal(loading.progress,.4);loading.update(1);assert.equal(loading.progress,1);loading.hide();assert.equal(loading.visible,false);loading.show();assert.equal(loading.progress,0);loading.fail(Error('test failure'));assert.equal(view.attributes['aria-busy'],'false');assert.ok(content.children[0].textContent.includes('載入失敗'));
async function checkArtwork(){await loading.ready;const another=sandbox.createLoadingScreen();await another.ready;assert.equal(fetches,1);assert.equal(bitmaps,1);assert.equal(Object.keys(config.sprites).length,19);assert.equal(config.luna.frameTicks,6);assert.equal(config.bar.scale,.5);for(let cycle=0;cycle<3;cycle++)for(let index=0;index<10;index++){const peak=cycle*580+index*58+22;assert.equal(sandbox.loadingLetterPose(peak,index).y,-30);assert.equal(sandbox.loadingLetterPose(peak,(index+1)%10).y,0)}for(const [tick,expected] of [[0,'006000'],[5,'006000'],[6,'006001'],[60,'006000']]){draws.length=0;loading.render(tick);const frame=draws.find(entry=>entry.type==='image').args;assert.equal(frame[1],config.sprites[expected].x);assert.equal(frame[2],config.sprites[expected].y)}for(let index=0;index<10;index++){const start=index*58;assert.equal(sandbox.loadingLetterPose(start-1,index).alpha,1);assert.equal(sandbox.loadingLetterPose(start+22,index).y,-30);assert.equal(sandbox.loadingLetterPose(start+42,index).y,14);assert.ok(sandbox.loadingLetterPose(start+57,index).y===0);if(index<9)assert.equal(sandbox.loadingLetterPose(start+57,index+1).alpha,1)}
loading.show();loading.update(.5);draws.length=0;loading.render(580);const pink=draws.find(entry=>entry.type==='fill'&&entry.color==='#FF3EA7'),frame=draws.findIndex(entry=>entry.type==='image'&&entry.args[1]===config.sprites.LoadingBar.x&&entry.args[2]===config.sprites.LoadingBar.y);assert.deepEqual(pink.args,[257,464,384.5,32]);assert.ok(draws.indexOf(pink)<frame);const luna=draws.find(entry=>entry.type==='image').args;assert.ok(Math.abs(luna[7]-config.sprites['006000'].w*630/1080)<1e-8);const numberPositions=config.letters.map(entry=>entry.x);assert.equal(numberPositions[0],465.75);assert.equal(numberPositions[9],1020.4033);let exited=0;loading.showTest(()=>exited++);loading.update(.6);content.children[4].children[0].click();assert.equal(loading.progress,0);assert.equal(loading.snapshot().test,true);assert.equal(loading.confirmTest(),true);assert.equal(exited,1);assert.equal(loading.visible,false);console.log('Loading atlas preload/deduplication, sequential bounce, pink underlay, Luna scale and preview restart passed')}
checkArtwork().catch(error=>{console.error(error);process.exitCode=1});
const startLine=fs.readFileSync(path.join(root,'Engine/palace-menu.js'),'utf8').split(/\r?\n/).find(line=>line.includes('async function start(next,choice)'));
(async()=>{let resolveReady,readyCalls=0,onProgress,failure;const battle={logoIntro:{finished:true},starting:false,mode:'select',selection:{hide(){}},acs:{hide(){}},panel:{replaceChildren(){}},loading:{show(){this.visible=true},update(value){this.progress=value},hide(){this.visible=false},fail(error){failure=error}},api:{pause(value){battle.paused=value},ready(callback){readyCalls++;onProgress=callback;return new Promise(resolve=>{resolveReady=resolve})},start(){battle.started=true}},options:{timer:'99'},overlay:{hidden:false},music:{pause(){}},showHome(){},console,requestAnimationFrame:callback=>callback()};vm.createContext(battle);vm.runInContext(startLine+';globalThis.start=start',battle);const pending=battle.start('vs');assert.equal(battle.loading.visible,true);assert.equal(battle.paused,true);onProgress(.6);assert.equal(battle.loading.progress,.6);await battle.start('vs');assert.equal(readyCalls,1);assert.equal(battle.started,undefined);resolveReady();await pending;assert.equal(battle.started,true);assert.equal(battle.loading.visible,false);assert.equal(battle.loading.progress,1);assert.equal(battle.paused,false);battle.api.ready=async()=>{throw Error('test failure')};battle.console={error(){}};await battle.start('training');assert.equal(failure.message,'test failure');assert.equal(battle.loading.visible,true);assert.equal(battle.starting,false);console.log('Black loading page, real progress, duplicate start prevention, completion and failure passed')})().catch(error=>{console.error(error);process.exitCode=1});

