const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
function element(){return {style:{},children:[],attributes:{},hidden:false,appendChild(child){this.children.push(child)},setAttribute(key,value){this.attributes[key]=value},addEventListener(key,callback){this[key]=callback}}}
const sandbox={document:{body:element(),createElement:element}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'Engine/loading-screen.js'),'utf8').replace('export function','function')+';globalThis.createLoadingScreen=createLoadingScreen',sandbox);
const loading=sandbox.createLoadingScreen(),view=sandbox.document.body.children[0],bar=view.children[0].children[1];
assert.equal(loading.visible,false);assert.ok(view.style.cssText.includes('background:#000'));loading.show();assert.equal(loading.progress,0);loading.update(.4);assert.equal(bar.attributes['aria-valuenow'],'40');loading.update(.2);assert.equal(loading.progress,.4);loading.update(1);assert.equal(loading.progress,1);loading.hide();assert.equal(loading.visible,false);loading.show();assert.equal(loading.progress,0);loading.fail(Error('test failure'));assert.equal(view.attributes['aria-busy'],'false');assert.ok(view.children[0].children[0].textContent.includes('載入失敗'));
const startLine=fs.readFileSync(path.join(root,'Engine/palace-menu.js'),'utf8').split(/\r?\n/).find(line=>line.includes('async function start(next,choice)'));
(async()=>{let resolveReady,readyCalls=0,onProgress,failure;const battle={logoIntro:{finished:true},starting:false,mode:'select',selection:{hide(){}},panel:{replaceChildren(){}},loading:{show(){this.visible=true},update(value){this.progress=value},hide(){this.visible=false},fail(error){failure=error}},api:{pause(value){battle.paused=value},ready(callback){readyCalls++;onProgress=callback;return new Promise(resolve=>{resolveReady=resolve})},start(){battle.started=true}},options:{timer:'99'},overlay:{hidden:false},music:{pause(){}},showHome(){},console,requestAnimationFrame:callback=>callback()};vm.createContext(battle);vm.runInContext(startLine+';globalThis.start=start',battle);const pending=battle.start('vs');assert.equal(battle.loading.visible,true);assert.equal(battle.paused,true);onProgress(.6);assert.equal(battle.loading.progress,.6);await battle.start('vs');assert.equal(readyCalls,1);assert.equal(battle.started,undefined);resolveReady();await pending;assert.equal(battle.started,true);assert.equal(battle.loading.visible,false);assert.equal(battle.loading.progress,1);assert.equal(battle.paused,false);battle.api.ready=async()=>{throw Error('test failure')};battle.console={error(){}};await battle.start('training');assert.equal(failure.message,'test failure');assert.equal(battle.loading.visible,true);assert.equal(battle.starting,false);console.log('Black loading page, real progress, duplicate start prevention, completion and failure passed')})().catch(error=>{console.error(error);process.exitCode=1});
